### ISSUE TITLE
Verbatim depth

### ISSUE THREAD

**Issue by Daphnisd** [nvs-vocabs/P01#1]
Hi, 
In a dataset, the depth where a sample was taken is described in relative terms. E.G "2 meter above the sea floor", "at the thermocline", "1 meter below the sea surface" 

Could a  P01 be created for this? I was thinking something like:

Label: Depth [descriptive] of sampling or measuring activity below the sea surface. 
Definition: A description of the sampling depth below the surface. Values include "at thermocline", "2 m above the seafloor"

**Comment by gwemon** [comment]
Hi @Daphnisd, 
"1 meter below sea surface" and "2 meters above sea floor" are effectively vertical coordinates. I would suggest using http://vocab.nerc.ac.uk/collection/P01/current/ADEPZZ01/ for Depth below sea surface and give it the value of 1; and use  http://vocab.nerc.ac.uk/collection/P01/current/AHSFZZ01/ for Height above sea bed and give it the value of 2. 
Would that work?
For "at the thermocline" I am not sure what to suggest to be honest. I am not keen on creating a P01 for it without careful consideration. Could you keep it as free text? At least for the time being? I'll consult with colleagues.

**Comment by gwemon** [comment]
@Daphnisd  I thought further about this and I think it may be possible to create a P01 term along the line of, for example, http://vocab.nerc.ac.uk/collection/P01/current/SEDTYCAT/

maybe something like: "Description of sampling vertical location in the water column"
Definition: Textual information characterising the depth of sampling relative to a specific feature (eg thermocline, nutricline, sub-surface chlorophyll maximum, oxygen minimum).

**Comment by Daphnisd** [comment]
Hi Gwen. yes that would be great!

**Comment by gwemon** [comment]
DEPLVCAT	Description of sampling vertical location in the water body created. It will be published as http://vocab.nerc.ac.uk/collection/P01/current/DEPLVCAT/ in a few hours.

**Comment by dr-shorthair** [comment]
Should this issue be closed?
