### ISSUE TITLE
Resolve apparent duplication for Concentration of total nitrogen {total_N} {PON} per unit volume of the water body [particulate >unknown phase]

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#101]
The 2 P01 concepts concerned are:
http://vocab.nerc.ac.uk/collection/P01/current/NTOTZZZZ/
http://vocab.nerc.ac.uk/collection/P01/current/MDMAP013/

**Comment by roy-lowry** [comment]
This one comes down to a phase I went through when I was being pedantic about the identity of the measurement made on an SPM sample in an elemental analyser. Strictly speaking this is total nitrogen, but can anybody think of any inorganic nitrogen species in SPM?? So, we ended up with two codes for the same measurement - the only difference being that NTOTZZZZ documents the assumption that particulate organic nitrogen is a synonym for particulate total nitrogen in its definition. 
In retrospect this was a complication I should never have introduced so I can see justification for the deprecation of MDMAP013.

**Comment by roy-lowry** [comment]
Removing inorganic carbon from a sample is easy (acidification) but removing inorganic nitrogen is a different matter. Any inorganic nitrogen in SPM will be refractory so I can't think of any sample treatment that would remove it whilst leaving the organic nitrogen intact. I didn't read the whole paper (they want payment) but the only way I can think of to quantify the inorganic nitrogen would be to make measurements of total nitrogen (e.g. high-temperature ignition) and organic nitrogen (lower-temperature ignition) then difference the two.

**Comment by gwemon** [comment]
Having discussed this today at our group meeting and after some consideration, my proposal is as follows:
1- Replace "PON" by "TPN" in the preferred label of https://vocab.nerc.ac.uk/collection/P01/current/NTOTZZZZ/
i.e. Concentration of total nitrogen {total_N} {TPN} per unit volume of the water body [particulate >unknown phase]
2- Set Altlabel to "TPN" instead of PON
3- Add a the definition:  	"The amount (moles or mass) of nitrogen in any chemical forms contained in particulate material present in a water sample and retained on a filter of unknown type and size. This quantity is sometimes labelled "PON" for Particulate Organic Nitrogen (i.e. nitrogen in compounds containing carbon atoms) when assumption is made that inorganic nitrogen content in suspended particulate material is zero or negligible." 
4- deprecate https://vocab.nerc.ac.uk/collection/P01/current/MDMAP013/ and replace by https://vocab.nerc.ac.uk/collection/P01/current/NTOTZZZZ/
5- replace all "PON" tags by "TPN" in the preflabels of all other codes set up for Concentration of total nitrogen in various particulate phases of water samples (N=14).

**Comment by roy-lowry** [comment]
The primary concern in the days before the definitions were routinely searched was to ensure that the concepts were found by searches for 'PON' and so the practice of referring to TPN as PON was established. Now that the definitions are routinely searched I'm happy with the suggested actions as the text 'PON' and 'Particulate Organic Nitrogen'  are in the definitions to allow the concepts to be found.

**Comment by SLBlakeman** [comment]
All changes have been made as per Gwen's message. 
https://vocab.nerc.ac.uk/collection/P01/current/NTOTZZZZ/ has been updated to: 
Concentration of total nitrogen {total_N} {TPN} per unit volume of the water body [particulate >unknown phase]

https://vocab.nerc.ac.uk/collection/P01/current/MDMAP013/ has been deprecated and replaced by NTOTZZZZ
