### ISSUE TITLE
Align spelling of sulfur/sulfate with IUPAC nomenclature decision (i.e. "f" instead of "ph")

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#103]
Terms related to sulfur/sulfate in P01, S27, S03,  and S04 are spelt sulphur/sulphate. This reflects the different spellings in british english and american english however, for sullfur, there was an IUPAC decision in 1990 to use "sulfur" (see e.g. https://www.nature.com/articles/nchem.301).  So, in order to avoid further confusion, and in order to align with IUPAC, I am planning to update these terms to the sulfur/sulfate spelling.

**Comment by dr-shorthair** [comment]
Will you retain `sulphur/sulphate` as an `altLabel` (with `@en-gb`) ?

**Comment by roy-lowry** [comment]
Also other species to consider such as sulphide/sulfide, sulphonic acid/sulfonic acid that turn up with a search for %sulph% in S27.
