### ISSUE TITLE
NTR: Request for 1 PAR Upwelling P01 code (BODCNVS-1191)

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/P01#104]
We had a request for a new PAR term in P01 similar to 
https://vocab.nerc.ac.uk/collection/P01/current/DWIRRXZZ/, but specifying an upwelling radiometer. 

We have now loaded this term:

**Code**
DWIRRXZ1
**Preferred label:**
Raw signal (counts) of instrument output by cosine-collector upwelling PAR radiometer
**Description:** 
The raw output expressed in counts from an upward-facing cosine collector radiometer measuring the integrated light over PAR wavelengths.

It will be live on the NVS from 0730 UTC tomorrow morning at:
https://vocab.nerc.ac.uk/collection/P01/current/DWIRRXZ1/

**Comment by roy-lowry** [comment]
If a radiometer is measuring upwelling radiation then it is downward-facing, not upward-facing as specified in the Description,

**Comment by danibodc** [comment]
Thank you Roy, I will update this!
