### ISSUE TITLE
Chlorophyll concentration parameter for eReefs project (1 term)

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/P01#124]
Term to be created as:

- Concentration of chlorophyll-a per unit volume of the water body by model prediction

No constituent terms required. To be modelled based on the following:
http://vocab.nerc.ac.uk/collection/P01/current/CPHLMMMO/

**Comment by gwemon** [comment]
@JordanAthertonNOC  If we are consistent with CPHLMMMO then the matrix should be "water body". And I think that for modelled data this woud be the best choice. The ">unknown" phase is reserved for particulate material extracted from samples when we do not know what method was used.

**Comment by JordanAthertonNOC** [comment]
Will set mat as MAT00640.

**Comment by JordanAthertonNOC** [comment]
Omitting detail of phase (S23/24) from term, precedent provided in other remote sensing terms:
CHLMOOC5, CHLMEAL1, CHLMEOC5, CHLAMSAT

**Comment by JordanAthertonNOC** [comment]
One new P01 code created:

[Concentration of chlorophyll-a {chl-a CAS 479-61-8} per unit volume of the water body by model prediction](http://vocab.nerc.ac.uk/collection/P01/current/CPHLMOD1)
