### ISSUE TITLE
NTR for Identifier, length and width of single particles in water bodies

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#127]
Related to https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/18

**Comment by gwemon** [comment]
The new P01 terms will use the following property terms:
http://vocab.nerc.ac.uk/collection/S06/current/S0600156/
http://vocab.nerc.ac.uk/collection/S06/current/S0600015/
http://vocab.nerc.ac.uk/collection/S06/current/S0600155/

Because this applies to single particles, we are proposing to add a new term to the S29 vocabulary for "single particle".

We envisage that the P01 preferred labels once compiled will be of the form:
Identifier of single particle in the water body
Width of single particle in the water body
Length of single particle in the water body

It could be debated whether we need to specify the matrix here since the properties reported are solely targeted at a single particle and the variable measured is not dependent on the medium in which the particle is. Could we use the same P01 codes if the particles where e.g. in sediments or in biota? Or do we need to be able to differentiate them at the CDI and hence P02 level? @mmolinajack what would your preference be?

**Comment by mmolinajack** [comment]
Hi @gwemon, in our opinion the definition of these 3 new P01s is independent of the matrix where the particles are measured

**Comment by gwemon** [comment]
Thanks @mmolinajack I think we will need a new P02 code for these new P01 codes. Maybe one that regroups single particle properties. I'll submit a proposal to the P02 governance.

**Comment by mmolinajack** [comment]
Ok, thank you!

**Comment by gwemon** [comment]
The following three new P01 codes have been queued for publication of the NVS:
SPLGXX01	Length of single particle in the water body
SPWDXX01	Width of single particle in the water body
SPIDXX01	Identifier of single particle in the water body

**Comment by mmolinajack** [comment]
Hi @gwemon,
we had agreed that these P01s can be independent of the measured matrix, right?
Thanks!

**Comment by gwemon** [comment]
> 

Thanks @mmolinajack  I completely forgot this. The terms are not yet public so I will amend them.

**Comment by gwemon** [comment]
https://vocab.nerc.ac.uk/collection/P01/current/SPLGXX01/
https://vocab.nerc.ac.uk/collection/P01/current/SPWDXX01/
https://vocab.nerc.ac.uk/collection/P01/current/SPIDXX01/
