### ISSUE TITLE
Parameter discovery (P02) mapping correction for nitrogen in sediments

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#158]
Correction needed for mapping of 4 P01 codes: IC000155, IC000140, IC000142, MAMR0051 from [RMIN](http://vocab.nerc.ac.uk/collection/P02/current/RMIN/) to [NTSD](https://vocab.nerc.ac.uk/collection/P02/current/NTSD/)

**Comment by danibodc** [comment]
Mappings have been updated and are live on the NVS.
