### ISSUE TITLE
NTR for chlorophyll a and phaeopigment concentrations in water bodies (BODCNVS-1232)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#173]
We need 6 new codes based on http://vocab.nerc.ac.uk/collection/P01/current/SPHAFLPB/
but for the following size fractions:  >1um, >3um, >10um, GF/F-1um, GF/F-3um, GF/F-10um

And 4 new codes for chlorophyll-a based on http://vocab.nerc.ac.uk/collection/P01/current/CPHLFLP1/
but for the following factions: >1um, >3um, GF/F-1um, and GF/F-3um 

As part of the work on SIMM vocab mapping

**Comment by gwemon** [comment]
@JordanAthertonNOC many thanks for taking this on. Also needed is a code for the fraction GF/F-1um baed on http://vocab.nerc.ac.uk/collection/P01/current/SPHASPPM/ i.e. where the methodology is "filtration, acetone extraction and spectrophotometry and processing following the Lorenzen protocol" - for this reason I updated he title of this ticket.

**Comment by JordanAthertonNOC** [comment]
11 new P01 codes created, anticipated to go live on the NVS by 07:00 BST tomorrow.

[Concentration of chlorophyll-a {chl-a CAS 479-61-8} per unit volume of the water body [particulate GF/F-3um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/CPHLFAF4)
[Concentration of chlorophyll-a {chl-a CAS 479-61-8} per unit volume of the water body [particulate GF/F-1um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/CPHLFAF3)
[Concentration of chlorophyll-a {chl-a CAS 479-61-8} per unit volume of the water body [particulate >3um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/CPHLFAF2)
[Concentration of chlorophyll-a {chl-a CAS 479-61-8} per unit volume of the water body [particulate >1um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/CPHLFAF1)
[Concentration of phaeopigments {pheopigments} per unit volume of the water body [particulate GF/F-3um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/SPHAFAF5)
[Concentration of phaeopigments {pheopigments} per unit volume of the water body [particulate GF/F-1um phase] by filtration, acetone extraction and spectrophotometry and processing following the Lorenzen protocol](http://vocab.nerc.ac.uk/collection/P01/current/SPHAFASL)
[Concentration of phaeopigments {pheopigments} per unit volume of the water body [particulate GF/F-1um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/SPHAFAF4)
[Concentration of phaeopigments {pheopigments} per unit volume of the water body [particulate >10um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/SPHAFAF3)
[Concentration of phaeopigments {pheopigments} per unit volume of the water body [particulate >3um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/SPHAFAF2)
[Concentration of phaeopigments {pheopigments} per unit volume of the water body [particulate >1um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/SPHAFAF1)
[Concentration of phaeopigments {pheopigments} per unit volume of the water body [particulate GF/F-10um phase] by filtration, acetone extraction and fluorometry](http://vocab.nerc.ac.uk/collection/P01/current/SPHAFAF6)
