### ISSUE TITLE
NTR: identifier of repeat analysis on sediment core samples (BODCNVS-1559)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#175]
We have received a request from Ifremer for a new P01 code to capture identifiers of repeat analysis on sediment core samples. The analysis are performed on the same sample and using the same methodology however they may be performed by different originators or at different times after the sample was collected and stored.  

It should be possible to create a new P01 under the P02 grouping [ACYC](http://vocab.nerc.ac.uk/collection/P02/current/ACYC/)

We are proposing the following term:
[Identifier](http://vocab.nerc.ac.uk/collection/S06/current/S0600156/) of repeat analysis

where [repeat analysis] is a new term needed in the S29 vocabulary that could be defined as follows:
"An analysis that is performed multiple times in time and does not qualify as true replicate analysis."

If so maybe we could also consider defining a P01 for: Identifier of replicate analysis? or is the differenciation between "replicate" and "repeat" analysis unnecessary?

**Comment by roy-lowry** [comment]
Hi Gwen,

Couldn't you simply have 'Identifier of analysis' with analysis defined as a measurement or set of measurements on a sample? The semantics of repetition would be shown by the existence of multiple instances of an identifier for a sample.

Cheers, Roy.

**Comment by gwemon** [comment]
Hi @roy-lowry  you're probably right. I guess my reasoning was trying to guard against users thinking these were true replicate analyses. i.e. performed in as identical conditions as possible in order to establish a measurement standard error or standard deviation.

**Comment by gwemon** [comment]
Hi @roy-lowry at our P01 review meeting today we decided to go for your suggestion. As a definition of "analysis" I'd suggest adding sub-sample as in: "A measurement or set of measurements on a sample or sub-sample."

**Comment by roy-lowry** [comment]
Looks good to me.  Cheers, Roy.

**Comment by JordanAthertonNOC** [comment]
One new P01 term created, anticipated to go live at ~07:00 BST tomorrow.

  IDANSIS1 [Identifier of analysis] (http://vocab.nerc.ac.uk/collection/P01/current/IDANSIS1)
