### ISSUE TITLE
NTR for Area of sampling event (BODCNVS-1583)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#177]
Relates to: https://github.com/inbo/esas2obis/issues/19
Will impact remodelling of terms mentioned in: https://github.com/nvs-vocabs/S18/issues/2 since we are now proposing to make a distinction between "sampling event" and "sample" when remodelling the following terms.

Not an easy one to make! Alternatively we can go for a unique "sample" term for all. So "Area of sampling event" would become "Area of sample". Personally I find the later ambiguous. I have copied below some of the terms related to this that still need modelling according to the PUV semantic model.

[PEWCXX02](https://vocab.nerc.ac.uk/collection/P01/current/PEWCXX02/) Dry weight of sample
by making it a combination of [S06 for dry weight](http://vocab.nerc.ac.uk/collection/S06/current/S0600148/) and the new S18/S29 term
[NEWCXX02](https://vocab.nerc.ac.uk/collection/P01/current/NEWCXX02/) Wet weight of sample >> Same as above but for wet weight
[VOLWBSMP](https://vocab.nerc.ac.uk/collection/P01/current/VOLWBSMP/) Volume sampled of the water body >> new preflabel would become: Volume of sample of the water body
[VOLSEDSM](https://vocab.nerc.ac.uk/collection/P01/current/VOLSEDSM/) Volume sampled of sediment >> new preflabel would become: Volume of sample of sediment
[AREABEDS](https://vocab.nerc.ac.uk/collection/P01/current/AREABEDS/) Area sampled of the bed >> Area of sample of the bed
[WASPXX01](https://vocab.nerc.ac.uk/collection/P01/current/WASPXX01/) Area sampled of the bed by image analysis >> Area of sample of the bed by image analysis
[SAMPARAC](https://vocab.nerc.ac.uk/collection/P01/current/SAMPARAC/) | Sample area (aircraft survey) >> Area of sampling event  by aircraft survey or **ALTERNATIVELY** Area of sample?
[VOLFFMXX](https://vocab.nerc.ac.uk/collection/P01/current/VOLFFMXX/) | Sample volume (filtration) by flow meter >> Volume of sample of water body by filtration and flow meter
[VOLSPOPC](https://vocab.nerc.ac.uk/collection/P01/current/VOLSPOPC/) | Sample volume (optical plankton recorder count) >> Volume of sample of water body by optical plankton recorder

**Comment by gwemon** [comment]
Decision from P01 vocab group meeting today is to define a P01 code for "Area of survey". So we will need an S18/S29 term for survey as well as sample. @roswri can I leave this with you to create what's needed and contact @peterdesmet? BODCNVS Jira ticket is: [BODCNVS-1583](https://jira.ceh.ac.uk/browse/BODCNVS-1583)

**Comment by peterdesmet** [comment]
👋 Has this `Area of sample` term been added?

**Comment by gwemon** [comment]
Sorry @peterdesmet it looks like this got forgotten. We'll get this done for you today.

**Comment by peterdesmet** [comment]
Thanks! Keep me posted :-)

**Comment by gwemon** [comment]
@peterdesmet Term is now available from the NVS as http://vocab.nerc.ac.uk/collection/P01/current/SAMPARAX/
Thank you for your patience.

**Comment by gwemon** [comment]
Modifications to legacy terms were also necessary to bring them in line with the BODC P01 semantic model. The following terms are now all mapped to their component vocabularies (missing definitions will be added later):
<html>
<body>


Identifier | Preferred label | Alternative label | Definition | Date
-- | -- | -- | -- | --
[SAMPARAX](https://vocab.nerc.ac.uk/collection/P01/current/SAMPARAX/) | Area of survey {surveyed area} | SampArea | The areal extent of a survey of any kind of environment (matrix) using an unspecified method. | 2023-02-16
[WASPXX01](https://vocab.nerc.ac.uk/collection/P01/current/WASPXX01/)  | Area of sample {sampled area} from the bed by image analysis | AreaBedSamp_ImageAnalysis | Unavailable | 2023-02-16
[AREABEDS](https://vocab.nerc.ac.uk/collection/P01/current/AREABEDS/)  | Area of sample {sampled area} from the bed | AreaBedSamp | The area of the seabed or shore observed or sampled, such as the area of a box core. | 2023-02-16
[SSARNAXT](https://vocab.nerc.ac.uk/collection/P01/current/SSARNAXT/)  | Surface area of particles per unit dry weight of sediment by drying and nitrogen absorption | BulkSedSurfArea | Unavailable | 2023-02-16
[NEWCXX01](https://vocab.nerc.ac.uk/collection/P01/current/NEWCXX01/)  | Area of representative sample | RepArea | The area over which the measurements made are considered to be representative. | 2023-02-16
[SAMPARAC](https://vocab.nerc.ac.uk/collection/P01/current/SAMPARAC/)  | Area of survey {surveyed area} by aerial survey | SampArea_AirSurv | The areal extent of the portion of the Earth's surface included in a given sampling event (such as an animal count) from an aircraft | 2023-02-16

**Comment by peterdesmet** [comment]
Thanks, it is now used by ESAS and I can close https://github.com/inbo/esas2obis/issues/19 🎉
