### ISSUE TITLE
NTR for visibility (BODCNVS-1581)

### ISSUE THREAD

**Issue by peterdesmet** [nvs-vocabs/P01#178]
_See discussion at https://github.com/inbo/esas2obis/issues/20_: In the European Seabirds At Sea (ESAS) database, we have a term [visibility](https://esas-docs.ices.dk/tables/#position.visibility) defined as:

> Visibility (in km). Use a range code (A-D) for historical data.

Visibility is recorded because it can affect the quality of the identification of species.

I noticed three visibility related terms in BODC:

- **Horizontal visibility in the atmosphere by scattering photometer**: http://vocab.nerc.ac.uk/collection/P01/current/VISHOR01/ broader: Horizontal visibility
  > Maximum horizontal distance through the atmosphere at which an object can be seen and identified by the unaided eye estimated from the extinction coefficient measured by a scattering photometer.
- **Horizontal visibility (WMO code) in the atmosphere by visual estimation and conversion to WMO code using table 4300**: http://vocab.nerc.ac.uk/collection/P01/current/WMOCHVXX/ no definition, broader: Horizontal visibility (WMO code) (these codes are integers) and "visual estimation"
- **Horizontal visibility**: http://vocab.nerc.ac.uk/collection/S06/current/S0600244/
  > Maximum distance at which an observer can see and identify an object lying close to the horizontal plane on which he or she is standing. (source: AMS glossary, 20200219)

The latter is close to our definition, but is not part of P01. Would it be possible to have a more generic visibility term (cf. `S06/current/S0600244/`) in P01?

**Comment by SLBlakeman** [comment]
Hello @peterdesmet,

We can create the following term for you:

Horizontal visibility in the atmosphere by visual estimation. 

However, this will not be valid for use when someone has used the A,B,C,D ranges. If you would like, we could create the following term for these scenarios:

Horizontal visibility (ESAS code) in the atmosphere by visual estimation and conversion to ESAS code using the visibility table. 

We would then put the explanation of what constitutes the A,B,C,D ranges in the description of the P01. 

Please let me know how you would like to proceed.
Samantha

**Comment by peterdesmet** [comment]
Thanks @SLBlakeman, would range values such a `5-10` in "Horizontal visibility in the atmosphere by visual estimation." or only single integer/double values?

**Comment by SLBlakeman** [comment]
Hi @peterdesmet,
Apologies I should have clarified, the term "Horizontal visibility in the atmosphere by visual estimation" would have the units "metres". Therefore, the values for this code should be integers not ranges. It could be set as single or double integer. 
The only way we can incorporate ranges into a term is as I suggested previously:
 "Horizontal visibility (ESAS code) in the atmosphere by visual estimation and conversion to ESAS code using the visibility table." This would have "dimensionless" units and we provide the definition of the A-D ranges as stated by ESAS (<1, 1-5, 5-10, >10).
 Does this answer your question? Do you agree with the two proposed terms?

**Comment by peterdesmet** [comment]
The visibility values in ESAS are historically stored as letters (A-D), but we now allow **single** numeric values as well. So in the ESAS database, we have a mix of `A`, `B`, `0.1`, etc.

When transforming the data for OBIS, I opted to translate the letters to a range (e.g. `B` -> `5-10`) as I thought it easier to understand and it allows me to set the unit to `km` for all. I can also opt to leave the original values as is (`A`, `B`, `0.1`) and only set the unit for numeric values. I would then use the second term you suggest:

> Horizontal visibility (ESAS code) in the atmosphere by visual estimation and conversion to ESAS code using the visibility table.

Or would that term only apply to the letter values, with numeric values using the generic "Horizontal visibility in the atmosphere by visual estimation." term?

I hope this is clear 😅

**Comment by SLBlakeman** [comment]
Hi Peter,

Thank you for your message, I now understand where you are coming from. From our standpoint, the single numeric values (0.1, 0.2), ESAS code letters (A,B), and numeric ranges (5-10 km) should all be assigned separate P01 terms. 
Therefore, the generic term 
 "Horizontal visibility in the atmosphere by visual estimation." would only apply to the single numeric values, and the term "Horizontal visibility (ESAS code) in the atmosphere by visual estimation and conversion to ESAS code using the visibility table." to the letter values. If you would like a term for the data that are expressed as a range then we would need a separate code again. 
 
Hope this makes sense.

**Comment by peterdesmet** [comment]
Thanks Samantha, that makes sense. In that case we would need two terms as you suggest and I would use them as follows:

- **Horizontal visibility in the atmosphere by visual estimation.** I will use this if the content is a numeric value and convert it to meters (0.1 -> 100)
- **Horizontal visibility (ESAS code) in the atmosphere by visual estimation and conversion to ESAS code using the visibility table.** I will use this if the content is a letter (A, B, C, D) and not translate it to a numeric range, but leave it as is.

**Comment by SLBlakeman** [comment]
Hi Peter,

I've created the following terms and they are now available on the NVS:

[Horizontal visibility (ESAS code) in the atmosphere by visual estimation and conversion to ESAS code using the visibility table](http://vocab.nerc.ac.uk/collection/P01/current/VISHOR04)	Atmospheric visibility and transparency

[Horizontal visibility in the atmosphere by visual estimation](http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03)	Atmospheric visibility and transparency

Just to let you know, the units for the VISHOR03 can be any of the distance units (metres, kilometres, etc.), they are only established specifically as metres for BODC internal use. 

Please let me know if you have any other questions or concerns.

Thanks,
Samantha

**Comment by peterdesmet** [comment]
Thanks! I only have one minor concern regarding the definition, which is the inclusion of "identified by the unaided eye." In most cases binoculars are used to identify, does that invalidate the definition. Maybe it's easier to define as:

> Maximum horizontal distance through the atmosphere at which an object can be seen by eye.

**Comment by SLBlakeman** [comment]
Hi Peter,

Thank you for pointing this out, we have now updated the definitions for the horizontal visibility codes to exclude the expression "unaided", as it is more restricting than the P01 term. These should be available on the NVS by tomorrow morning (6th Dec 8am).

Thanks.
