### ISSUE TITLE
NTR: Haversine Distance

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/P01#179]
Would appreciate a discussing on a new term being created in P01:

Haversine distance - the angular distance between two points on the surface of a sphere. 

This term was used when describing the length of a trawl operation in the ocean. Unit of measurement would typically be kilometers or nautical miles. I am not sure whether Length of sampling track (http://vocab.nerc.ac.uk/collection/P01/current/LENTRACK/) would suffice in this instance, as I think this would not be the _angular_ distance?

**Comment by gwemon** [comment]
We will look into it @timvdstap

**Comment by gwemon** [comment]
We could maybe construct a P01 of the form: "Length of track by computation using the harversine formula" where "computation using the harversine formula" would be a new term in our S05 vocabulary (see e.g. https://vocab.nerc.ac.uk/search_nvs/S05/).

**Comment by timvdstap** [comment]
Hi @gwemon I think that sounds like a great idea! Thank you :)

**Comment by danibodc** [comment]
https://github.com/nvs-vocabs/S05/issues/15

**Comment by danibodc** [comment]
https://github.com/nvs-vocabs/S18/issues/15

**Comment by danibodc** [comment]
This term has now been loaded to P01 and will be live on the NVS from 0730 UTC tomorrow morning:

LENSMTRK	Length of sampling track by computation using the haversine formula

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/P01/current/LENSMTRK/
