### ISSUE TITLE
NTR total nitrogen based on Kjeldahl method applied to dissolved phase with unknown separation method  (BODCNVS-1232)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#184]
For Kjeldahl method see: https://en.wikipedia.org/wiki/Kjeldahl_method
Create new code based on a modification of: http://vocab.nerc.ac.uk/collection/P01/current/NTOTKJM1/
But using matrix http://vocab.nerc.ac.uk/collection/S26/current/MAT00626/

**Comment by SLBlakeman** [comment]
Term available on the NVS:
https://vocab.nerc.ac.uk/collection/P01/current/NTOTKJDX/
