### ISSUE TITLE
NTR for green tide parameters (BODCNVS-1673)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#190]
We received a request to create P01 codes for the following parameters (numbered):
Surface of the studied area impacted by the green tide pollution (2 parameters depending of the Ulva morphology)
1- Surface impacted by Ulva (ITIS: 1753: WoRMS 1944296) in blade, (by GIS calculation, unit: square metres)
2- Surface impacted by Ulva (ITIS: 1753: WoRMS 1944296) in blade + filamentous , by GIS calculation, unit: square metres
Theoretical surface covered by the green tide pollution as equivalent to 100% coverage, by GIS calculation, unit: square metres
3- Theoretical surface covered by Ulva (ITIS: 1753: WoRMS 1944296) in blade as equivalent to 100% coverage, by GIS calculation, unit: square metres
4- Theoretical surface covered by Ulva (ITIS: 1753: WoRMS 1944296) in blade + filamentous as equivalent to 100% coverage, by GIS calculation, unit: square metres
Type of stranding of the green tide pollution
5- Type of stranding of Ulva (ITIS: 1753: WoRMS 1944296) (visual evaluation, 3 values (free text) :'continuous carpet of Ulva','>30% of the total algae deposition','<30% of the total algae deposition', no unit)

**Comment by gwemon** [comment]
For the parameters 3 and 4, we could have:
[Area] of Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade; Subgroup: bloom]} on the water body plus ground by aerial photography and GIS calculation and summation of areas with 100% coverage. 
[Area] of Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade+filamentous; Subgroup: bloom]} on the water body plus ground by aerial photography and GIS calculation and summation of areas with 100% coverage.

**Comment by gwemon** [comment]
For the final parameter, 
"Type of stranding of Ulva (ITIS: 1753: WoRMS 1944296) (visual evaluation, 3 values (free text) :'continuous carpet of Ulva','>30% of the total algae deposition','<30% of the total algae deposition', no unit)"

this is effectively a categorisation of the macroalgal stranding based on visual observation and an arbitrary relative scale

Initial proposal is to model the P01 code as follows:
Relative cover category of Ulva (ITIS: 6559: WoRMS 144296) [Subgroup: stranding]} by visual estimation of target taxon dominance  (100%, >30%, <30%)

**Comment by roy-lowry** [comment]
Back again...

Looking at 3 and 4 my understanding of the meaning of 'bloom' in 1 and 2 has shifted from an expression of a high concentration of algae to a contiguous subset of the Earth's surface affected containing Ulva at a given point in time. I think that makes the way you're proposing to incorporate 'bloom' shoe-horning in the extreme.

This is changing making me think more in terms of 'Area containing' or 'Area affected by' for (1 and 2) and 'Area covered by' for (3 and 4).

I might also suggest using the existing 'Earth' for the matrix rather than 'water body + ground' as the two mean pretty much the same to me.

**Comment by roy-lowry** [comment]
Your approach to 5 is what I would have done.

Hope this helps. If you want to attract my attention to discuss any of these either e-mail Gmail or use the VMG chat on Teams.

Cheers, Roy.

**Comment by gwemon** [comment]
Thank you @roy-lowry All very good points!

**Comment by gwemon** [comment]
@roy-lowry  Roy, just following on your comments: 
> Hi Gwen,
> I prefer 'area' to 'extent' as the latter could also possibly be linear with the dimension of length (m).
Yes I agree.
> I'm not convinced 'bloom' adds anything to the semantics unless it can be defined in terms of a concentration range.
It is not really possible to define a concentration range because it depends on the species we are looking at. For toxic species, a "bloom" will be related to "harmful algal bloom" and toxin-production, while for non-toxic diatoms "bloom" will be more likely related to spring bloom, and for green macroalgae like Ulva it will be more linked to "green tides". So the concept of bloom is relative to the type of species and not to a given concentration or abundance level.  The reason I wanted to add a term here for "bloom" is that the Object of interest here is the instance of a bloom of a given species and not the occurrence of the species itself. But maybe there is another way to convey this and avoid ambiguity. "bloom" might not be the best term.
> Is it possible to get 'Area covered by Ulva' within the constraints of the Semantic Model.
We could do that in the physical model but we would be shoehorning the concept of "matrix" I think.
So we could have [Area] of [Earth's surface] [covered by] [biota] {Ulva etc... Shape: blade}
where [Area] would come from S06, [Earth's surface] would come from S18/29, [biota] from S26 and [Ulva etc] from S25.
In this case, I don't think we would need to specify bloom. But I am not comfortable with using matrix='biota' to fit our use case.

**Comment by gwemon** [comment]
With regards to proposal to use "Earth" we have one precedent and this is: http://vocab.nerc.ac.uk/collection/P01/current/RSALLDNS/ (correction of the wrong unit association has been made)
So, yes, I agree that it makes sense to recommend using [Earth](http://vocab.nerc.ac.uk/collection/S26/current/MAT00710/) for this types of observations.

**Comment by gwemon** [comment]
Regarding #3 and #4 I received additional feedback from Ifremer. My interpretation is wrong.: "Actually the problem in the definition that you gave is that it seems to concern only areas with 100% coverage :  Which may not exist, that is why we think the the word "equivalent" is important.
[Area] of Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade; Subgroup: bloom]} on the water body plus ground by aerial photography and GIS calculation and summation of equivalent areas with 100% coverage.
I remind you the formula: 
Area of the water covered by the Taxon =  2 000m², coverage ration = 50%, => theoretical surface = 1 000 m² (2 000m²*0,5)."

I am leaning towards creating very specific S05 terms but I found "summation of equivalent areas with 100% coverage" difficult to understand.

Does the following have all the elements we need to describe the parameter?
"computation from total area covered by the taxon multiplied by the estimated coverage ratio"
Does maybe "GIS" belong more to the analysis part of the methodology rather than the post-processing?

If so we could have:
[Area] of [Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade; Subgroup: bloom]}] on the Earth by [aerial photography and GIS analysis] and [computation from total area covered by the taxon multiplied by the estimated coverage ratio]
Where [aerial photography and GIS analysis] would come from S04 and [computation etc] from S05

I am still struggling with a way to distinguish #1#2 and #3#4 other than by using the S05 element. 
If we go as suggested here then I feel that we would need to make #1#2 unambiguous too. i.e. find a way to clearly state that this is the total area affected by the bloom of Ulva. @roy-lowry @SLBlakeman maybe we could have a quick call later today to go through the various options.

**Comment by gwemon** [comment]
> Back again...
> 
> Looking at 3 and 4 my understanding of the meaning of 'bloom' in 1 and 2 has shifted from an expression of a high concentration of algae to a contiguous subset of the Earth's surface containing Ulva at a given point in time. I think that makes the way you're proposing to incorporate 'bloom' shoe-horning in the extreme.
> 
> This is making me think more in terms of 'Area containing' or 'Area affected by' for (1 and 2) and 'Area covered by' for (3 and 4).
> 
> I might also suggest using the existing 'Earth' for the matrix rather than 'water body + ground' as the two mean pretty much the same to me.

@roy-lowry  I think that adding "bloom" might be what could enable us to distinguish the 2 sets of parameters without breaking the semantic model logic and structure. This is because the first set of parameters represent the area covered by the bloom as the entity while the second set of parameters represent the area covered by Ulva spp biomass as an entity. So we would exclude "bloom" from the second set of parameters but we would need to keep it for the first set or find another way to make the distinction between these 2 quantities.

**Comment by roy-lowry** [comment]
Hi Gwen,

Had a screw-up with Teams this morning when it automatically put me into the Data Services meeting whilst a guy was in the room giving a quote for window blinds!! I quickly shut it down, but now I can't get to the VMG chat any more.

Although I possibly didn't express it clearly the Ifremer feedback fits with what was in my mind. If a green tide affected all parts of a 1000 m2 water body but only 25% of the area is green then 3/4 would refer to the 'area covered' i.e. 250 m2 whilst the 'area containing'/'area occupied'/'area affected' would be the whole 1000 m2 of the water body.

Wkipedia defines algal bloom as 'a rapid increase or accumulation in the population of algae'. What we need is language to specify the spatial extent. Thinking..... How about 'Bloom spatial extent' (The area of a contiguous subset of Earth's surface affected by a rapid increase in algal population)

**Comment by roy-lowry** [comment]
That could give:

Bloom spatial extent of [Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade] on the Earth by [aerial photography and GIS analysis] and [computation from total area covered by the taxon multiplied by the estimated coverage ratio]

For (1)

I then like your idea of losing the word 'bloom' from 3/4 giving 'Area covered by.......'

Cheers, Roy.

**Comment by roy-lowry** [comment]
Copied the wrong data production and data analysis segments in the above....

Think it should have been:

Bloom spatial extent of [Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade] on the Earth by aerial photography and GIS analysis

**Comment by SLBlakeman** [comment]
Yesterday in the P01 meeting we discussed using the term: Area coverage for terms 1 and 2. We have a term that already uses "Proportional coverage" which we discussed using for when the coverage is in %. The term has not been migrated and other similar P01s just use "Coverage", but we talked about changing them to "Proportional coverage". 
This way we would have Area coverage (m^2). What do you think @roy-lowry? 
Term 1:
Area coverage of  [Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade, Subgroup: bloom] on the Earth by [aerial photography and GIS analysis].  I think including bloom in 1 and 2 and leaving it out in term 3 and 4 is a great idea. 
Term 2:
Area coverage of  [Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade+filamentous, Subgroup: bloom] on the Earth by [aerial photography and GIS analysis].  

I think including bloom in terms 1 and 2 and leaving it out of terms 3 and 4 is a great idea. I also think @gwemon your definitions for terms 3 and 4 are great, I would leave them as is:
Term 3:
[Area] of [Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade; Subgroup: bloom]}] on the Earth by [aerial photography and GIS analysis] and [computation from total area covered by the taxon multiplied by the estimated coverage ratio]
Term 4:
[Area] of [Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade+filamentous; Subgroup: bloom]}] on the Earth by [aerial photography and GIS analysis] and [computation from total area covered by the taxon multiplied by the estimated coverage ratio]

**Comment by roy-lowry** [comment]
I think 'Area coverage' is semantically much closer to terms 3 and 4 than to 1 and 2.  Terms 1 and 2 are the area of a spatial object that is partially covered and partially clear. Terms 3 and 4 describe the total area within the spatial object that is covered by the taxon.

I think we need to get 'bloom' away from the subgroup because the way the word is being used in this context is to describe a contiguous chunk of the Earth's surface in which there is a rapid increase in algal abundance. I can't see how that can be a subgroup of a taxon.  Additionally, in this context the word 'bloom' has no place in terms 3 and 4. There seems to be general agreement on this but the word is still there in the last comment from @SLBlakeman

**Comment by SLBlakeman** [comment]
My mistake, I did indeed leave the "bloom" subgroup in the terms 3 and 4, I've edited my previous comment to avoid future confusion. 

I understand where you're coming from @roy-lowry and if you're comfortable with having "bloom" in the S06, which I guess isn't any different than having "Cell volume", then I agree that it will help to clarify the term. I know we said previously that "extent" was ambiguous as it could be length, but I do think "Bloom spatial extent" describes the term in an intuitive way, whereas I think even "Bloom area" could be too similar to terms 3 and 4 and lead to confusion.

**Comment by gwemon** [comment]
Thank you @SLBlakeman @roy-lowry. That is all very helpful. I'll need to give it some thoughts. I am not comfortable with having "bloom" in an S06 concept because it breaks our alignment with the I-ADOPT ontology and with our model too. S06 should be as clean to being a quantity or property kind as possible, free of concepts that could be considered the object of interest of an observation. While we do have some examples where this rule is already shaken (legacy terms such as Cell volume or some of the "Waves" parameters), I am not keen to create more if we can avoid. 
Ideally what we create for this Ulva use case should enable us to re-use the same S06 (property of an object) for other types of areal observations of continuous or discontinuous covers on the earth surface like e.g. ice cover or oil spill. I have the feeling we might need to adapt our GP model for this in the long term. i.e. enable a generic object of interest defined in S18/
S29 (in this case it would be a bloom or a stranding etc...) to be associated with a S25 entity that further qualify that object if required. Needs thinking time! But while this might be possible in the long term, in the mean time, we need to create something that enables us to give Ifremer P01 codes that are as accurate as we can even if not perfect.

**Comment by roy-lowry** [comment]
Areal extent works for me.

The difficulty here is down to a limitation in the semantic model, which doesn't allow for things like 'Areal extent of bloom of Ulva' to be built from three elements. Also Harry Dooley (the ICES hydrographer for many years) had the example of pigment concentration from the gut of a copepod taken from a herring's stomach when he wanted to wind up anybody talking about semantic modelling (usually me!!). This might be usefully borne in mind for any future model expansion.

**Comment by gwemon** [comment]
Thanks @roy-lowry yes, what I was proposing when I talked about extending the GP model was just that. i.e. to be able to have [a S06 property] of [a S29 object] of [a S25 biological entity] [in a S02 relation to] a [S26 matrix] by a [S03/S04/S05 method]

Which would then enable us to have: [Areal extent] of [bloom] of [Ulva {Shape etc}] [on the] [Earth] by [aerial photography and GIS analysis]

In the biological model we already have what's needed to model Harry Dooley's example but yes, it can get complicated!

**Comment by gwemon** [comment]
I think that the summary of our discussions, and bearing in mind that we cannot at this stage modify our existing semantic model, gives us the following 5 codes:

1- Areal extent of Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade; Subgroup: bloom]} on the Earth by aerial photography, GIS analysis

Proposed definition: Total surface of sea and ground affected by a macroalgal bloom of the blade morphotype from the genus Ulva, estimated from aerial photography and GIS processing. This kind of parameters is used in the monitoring of opportunistic macroalgal blooms such as "green tides".

2- Areal extent of Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade+filamentous; Subgroup: bloom]} on the Earth by aerial photography, GIS analysis

Proposed definition: Total surface of sea and ground affected by a macroalgal bloom composed of a combination of blade and filamentous morphotypes of the genus Ulva, estimated from aerial photography and GIS processing. This kind of parameters is used in the monitoring of opportunistic macroalgal blooms such as "green tides".

I decided to keep "bloom" in the S13 vocabulary and hence to have it as part of the biological entity definition because it was the only place it could be fitted at this stage without much impact and could be relocated later if we decide to change the GP model.

For parameter 3 and 4, I research "Area coverage" and saw that Area or areal coverage is often a proportion coverage. So to avoid confusion I am proposing to be very explicit and use "Coverage (as an area)". This will be defined in S06.

3- Coverage (as an area) of Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade]} on the Earth by aerial photography, GIS analysis and computation from total area occupied by the taxon multiplied by the estimated coverage ratio.

Proposed definition: Surface of sea and ground covered by the blade morphotype of the macroalgal genus Ulva estimated by aerial photography and GIS processing, estimated by excluding area within the bloom where the target organism was absent or not dominant. This parameter is sometimes refer to as "Theoretical area" or "Theoretical surface". This kind of parameters is used in the monitoring of opportunistic macroalgal blooms such as "green tides".

4- Coverage (as an area) of Ulva (ITIS: 6559: WoRMS 144296) [Shape: blade+filamentous]} on the Earth by aerial photography, GIS analysis and computation from total area occupied by the taxon multiplied by the estimated coverage ratio.

5- Relative cover category of Ulva (ITIS: 6559: WoRMS 144296) [Subgroup: stranding]} on the Earth by visual estimation of target taxon dominance (100%, >30%, <30%)

**Comment by gwemon** [comment]
As a matter of interest on a related subject, this is an article about the difference between sea ice extent and area: https://nsidc.org/learn/ask-scientist/what-difference-between-sea-ice-area-and-extent

**Comment by gwemon** [comment]
The codes are now live on the NVS:
http://vocab.nerc.ac.uk/collection/P01/current/COVCATUV/
http://vocab.nerc.ac.uk/collection/P01/current/AAUVBB01/
http://vocab.nerc.ac.uk/collection/P01/current/AAUVBB02/
http://vocab.nerc.ac.uk/collection/P01/current/AXUVBB01/
http://vocab.nerc.ac.uk/collection/P01/current/AXUVBB02/

http://vocab.nerc.ac.uk/collection/P01/current/COVCATUV/ contains an error in the method fields which has been corrected. The concept will be updated overnight.

**Comment by gwemon** [comment]
The correction is now live on the NVS.
