### ISSUE TITLE
NTR: Sea-floor depth derived from global grid (BODCNVS-1714)

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/P01#192]
Term to be modelled as:
Sea-floor depth (below mean sea level) {bathymetric depth} in the water body by derivation from a global grid specified elsewhere

Based on the existing term:
[MBANGBCE](http://vocab.nerc.ac.uk/collection/P01/current/MBANGBCE/)

Will require the creation of one new [S06 term](https://github.com/nvs-vocabs/S06/issues/70).
Will require the creation of one new [S05 term](https://github.com/nvs-vocabs/S05/issues/18).

**Comment by JordanAthertonNOC** [comment]
Gwen investigating how sea floor depth parameters should best be modelled.

**Comment by danibodc** [comment]
It was decided to create this using our existing model until we have decided how to re-model the rest of the related sea-floor depth terms. It was also decided to remove the reference 'specified elsewhere'; this has been added to the description instead.

Term loaded to P01, will be live on the NVS from tomorrow morning:

MBANDVGR	Sea-floor depth (below mean sea level) {bathymetric depth} in the water body by derivation from a global grid

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/P01/current/MBANDVGR/
