### ISSUE TITLE
NTR: Cellular carbon content derived from flow cytometry data (BODCNVS-1740)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#194]
Relates to: https://github.com/nvs-vocabs/P06/issues/44

The proposal is to create a new P01 code of the form:
[Mass](http://vocab.nerc.ac.uk/collection/S06/current/S0600042/) of [carbon](http://vocab.nerc.ac.uk/collection/S27/current/CS002836/) per cell of [biota](http://vocab.nerc.ac.uk/collection/S26/current/MAT01963/) {[biological entity specified elsewhere](http://vocab.nerc.ac.uk/collection/S25/current/BE007117/)}
or maybe more accurately:
[Mass](http://vocab.nerc.ac.uk/collection/S06/current/S0600042/) of [organic carbon](http://vocab.nerc.ac.uk/collection/S27/current/CS002857/) per cell of [biota](http://vocab.nerc.ac.uk/collection/S26/current/MAT01963/) {[biological entity specified elsewhere](http://vocab.nerc.ac.uk/collection/S25/current/BE007117/)}
Also proposing to add the tag "cellular carbon content" inside the P01 preferred label.
Possibility of making this code more specific to the methodology used.
A new S02 linking the observed phenomena to the matrix will be needed for "per cell".

**Comment by danibodc** [comment]
Biomass as carbon (biological entity specified elsewhere) per unit volume of the water body by flow cytometry

**Comment by danibodc** [comment]
Mass of organic carbon per cell of biota {biological entity specified elsewhere}

**Comment by jakjonbodc** [comment]
Created P01 term 'Mass of organic carbon {organic_C CAS 7440-44-0} {cellular carbon content} per cell of biota {biological entity specified elsewhere}' - MAOCCB11

http://vocab.nerc.ac.uk/collection/P01/current/MAOCCB11/
