### ISSUE TITLE
NTR: Biomass as carbon of biota per unit volume of the water body by flow cytometry (BODCNVS-1740)

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/P01#195]
Sort of related to [this ticket](https://github.com/nvs-vocabs/P01/issues/194), I propose the creation of another term:

[Biomass as carbon](http://vocab.nerc.ac.uk/collection/S06/current/S0600272/) of [biota](http://vocab.nerc.ac.uk/collection/S26/current/MAT01963/) {[biological entity specified elsewhere](http://vocab.nerc.ac.uk/collection/S25/current/BE007117/)} [per unit volume of the](http://vocab.nerc.ac.uk/collection/S02/current/S053/) water body by [flow cytometry](http://vocab.nerc.ac.uk/collection/S04/current/S045/).

I've only been able to find really specific vocabulary (i.e. [this one](http://vocab.nerc.ac.uk/collection/P01/current/C419A00Z/)) which is kinda what I'm basing my more general proposed term on.

**Comment by jakjonbodc** [comment]
Editing parameter title to 'Biomass as carbon of biological entity specified elsewhere per unit volume of the water body by flow cytometry' after discussion with Gwen.

**Comment by jakjonbodc** [comment]
Created P01 term 'Biomass as carbon of biological entity specified elsewhere per unit volume of the water body by flow cytometry' - FCBIOL12

http://vocab.nerc.ac.uk/collection/P01/current/FCBIOL12/
