### ISSUE TITLE
Wrong unit suggested for the Biovolume CVOLUKNB (BODCNVS-1737)

### ISSUE THREAD

**Issue by jiho** [nvs-vocabs/P01#196]
Biovolume is
	http://vocab.nerc.ac.uk/collection/P01/current/CVOLUKNB/
The unit in the related section is #/ml
	http://vocab.nerc.ac.uk/collection/P06/current/UCML/
but according to the definition "Biovolume of biological entity specified elsewhere per unit volume of the water body" it should rather be a volume per unit volume.

I would suggest mm3/m3
	http://vocab.nerc.ac.uk/collection/P06/current/CMCM/
but any other units would work as long as it is volume/volume (or even a dimensionless unit: http://vocab.nerc.ac.uk/collection/P06/current/UPPM/ but being explicit would be better)

**Comment by gwemon** [comment]
Thank you @jiho. You're absolutely right. This is an error. I have corrected it and the update has been queued for our overnight publication on the NVS.
