### ISSUE TITLE
Request for "Biovolume of biological entity specified elsewhere" (BODCNVS-1743)

### ISSUE THREAD

**Issue by PatriciaCabrera** [nvs-vocabs/P01#198]
Is it possible to create "Biovolume of biological entity specified elsewhere"? Related unit ->  mm3. 

For our needs (imaging data), using "Biovolume of biological entity specified elsewhere per unit volume of the water body" http://vocab.nerc.ac.uk/collection/P01/current/CVOLUKNB/ ; is not appropriate to use this one, because we are not measuring a volume per unit volume.

**Comment by gwemon** [comment]
Thanks @PatriciaCabrera  we will pick this up tomorrow.

**Comment by danibodc** [comment]
Hi @PatriciaCabrera 

The new term has now been loaded to P01:

CVOLZZ01	Biovolume of biological entity specified elsewhere

It will be live on the NVS from tomorrow morning, many thanks.

**Comment by PatriciaCabrera** [comment]
Great thanks a lot!

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/P01/current/CVOLZZ01/
