### ISSUE TITLE
NTR: Preserved and fresh wet length of biological entity specified elsewhere (BODCNVS-1756)

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/P01#203]
Previous request received for Preserved wet weight: http://vocab.nerc.ac.uk/collection/P01/current/PWWBIOXX/1/ in contrast to the already existing fresh wet weight http://vocab.nerc.ac.uk/collection/S06/current/S0600088/

New request for equivalent Preserved wet length measurement and Fresh wet length measurement.  Currently the only measure is length http://vocab.nerc.ac.uk/collection/P01/current/OBSINDLX/.

**Comment by roswri** [comment]
Terms created:
OBSPRELX	Length of biological entity specified elsewhere [Subgroup: preserved]
OBSFRELX	Length of biological entity specified elsewhere [Subgroup: fresh]

**Comment by roswri** [comment]
http://vocab.nerc.ac.uk/collection/P01/current/OBSPRELX/
https://vocab.nerc.ac.uk/collection/P01/current/OBSFRELX/
