### ISSUE TITLE
NTR for additional sound pressure level parameter codes

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#21]
BODC ref BODCNVS-541
We have received a request for new sound pressure level parameter codes similar to:
AMBNSP11 - Sound pressure level of ambient noise (2000Hz-centred one-third-octave frequency band, 20s interval) relative to 1 micropascal in the water body

AMBNSP12 - Sound pressure level of ambient noise (125Hz-centred one-third-octave frequency band, 20s interval) relative to 1 micropascal in the water body

AMBNSP13 - Sound pressure level of ambient noise (63Hz-centred one-third-octave frequency band, 20s interval) relative to 1 micropascal in the water body

for the following 28 centred one-third-octave frequency bands [Hz]:
20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400, 500,630, 800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000, 6300, 8000 and 10000
and unspecified time-interval (or more specifically, time-interval specified elsewhere in the data model)

**Comment by danibodc** [comment]
BODCNVS-541: 28 new P01 terms created for a SeaDataCloud EMODnet Ingestion request for new sound pressure level terms that don't specify a time interval.

URL | Preferred   label
-- | --
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP14 | Sound pressure level   of ambient noise (20Hz-centred one-third-octave frequency band, time interval   specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP15 | Sound pressure level   of ambient noise (25Hz-centred one-third-octave frequency band, time interval   specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP16 | Sound pressure level   of ambient noise (31.5Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP17 | Sound pressure level   of ambient noise (40Hz-centred one-third-octave frequency band, time interval   specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP18 | Sound pressure level   of ambient noise (50Hz-centred one-third-octave frequency band, time interval   specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP19 | Sound pressure level   of ambient noise (63Hz-centred one-third-octave frequency band, time interval   specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP20 | Sound pressure level   of ambient noise (80Hz-centred one-third-octave frequency band, time interval   specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP21 | Sound pressure level   of ambient noise (100Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP22 | Sound pressure level   of ambient noise (125Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP23 | Sound pressure level   of ambient noise (160Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP24 | Sound pressure level   of ambient noise (200Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP25 | Sound pressure level   of ambient noise (250Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP26 | Sound pressure level   of ambient noise (315Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP27 | Sound pressure level   of ambient noise (400Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP28 | Sound pressure level   of ambient noise (500Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP29 | Sound pressure level   of ambient noise (630Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP30 | Sound pressure level   of ambient noise (800Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP31 | Sound pressure level   of ambient noise (1000Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP32 | Sound pressure level   of ambient noise (1250Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP33 | Sound pressure level   of ambient noise (1600Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP34 | Sound pressure level   of ambient noise (2000Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP35 | Sound pressure level   of ambient noise (2500Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP36 | Sound pressure level   of ambient noise (3150Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP37 | Sound pressure level   of ambient noise (4000Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP38 | Sound pressure level   of ambient noise (5000Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP39 | Sound pressure level   of ambient noise (6300Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP40 | Sound pressure level   of ambient noise (8000Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
http://vocab.nerc.ac.uk/collection/P01/current/AMBNSP41 | Sound pressure level   of ambient noise (10000Hz-centred one-third-octave frequency band, time   interval specified elsewhere) relative to 1 micropascal in the water body
