### ISSUE TITLE
Request for sediment (porewater) parameter definitions - hydrogen sulfide (BODCNVS-1810)

### ISSUE THREAD

**Issue by isanti** [nvs-vocabs/P01#210]
We noted that some terms are only defined in relation to a water body (water column).

For hydrogen sulfide, I find this term: http://vocab.nerc.ac.uk/collection/P01/current/H2SXZZXX/ but it is specific for water column water body.
But I cannot find a similar one for sediment or sediment porewater. It would be very useful as hydrogen sulfide is very often measured in sediment porewater.

**Comment by gwemon** [comment]
Thanks for your query @isanti. Indeed it looks like we only have P01 codes for H2S in water bodies. We can create a code for H2S measured in sediment pore water. Are the measurements referenced to volume of sediment pore water? or mass of sediment pore water?

**Comment by JordanAthertonNOC** [comment]
One new term created for H2S in sediment pore water:

[H2SSPWXX](http://vocab.nerc.ac.uk/collection/P01/current/H2SSPWXX/) Concentration of hydrogen sulfide {H2S CAS 7783-06-4} per unit volume of the sediment pore water [dissolved plus reactive particulate phase]
