### ISSUE TITLE
phytoplankton and bacteria median cell diameter P01's (BODCNVS-1814)

### ISSUE THREAD

**Issue by jakjonbodc** [nvs-vocabs/P01#211]
Request to VMG for new P01's for data representing the median diameter of cells of phytoplankton/ bacteria

I think that 'Diameter median of Prochlorococcus (ITIS: 610076: WoRMS 345515) per unit volume of the water body by ... ' would work. They have submitted data for prochlorococcus, synechococcus, Picoeukaryotes, Nanoeukaryotes and Heterotrophic bacteria so a new P01 would be required for each.

I'm not sure how the methodology would be described in a P01 code - it looks like they have ran the water sample through a number of filter sizes and used flow cytometry to measure the percentage of cells remaining after each filtration, they have determined the median cell diameter as being equal to the pore size at which 50% of the cells remain. They have determined this pore size by drawing a line from the 50% mark on the Y-axis (% cells remaining) and then drawing a line to the X-axis (pore size (um)) to determine the median cell size for the group.

**Comment by gwemon** [comment]
Hi @jakjonbodc We discussed this at the last VMG meeting and suggestion is to adopt: Diameter median of Prochlorococcus (ITIS: 610076: WoRMS 345515) in the water body by size fractionation and flow cytometry

**Comment by jakjonbodc** [comment]
heterotrophic bacteria diameter (um) max_permiss_val determined from the following: https://nocacuk-my.sharepoint.com/personal/sambla_noc_ac_uk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsambla%5Fnoc%5Fac%5Fuk%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files%2F3%2Ds2%2E0%2DB012227430X004931%2Dmain%2Epdf&parent=%2Fpersonal%2Fsambla%5Fnoc%5Fac%5Fuk%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files&ga=1

**Comment by jakjonbodc** [comment]
nanoeukaryotic cell diameter (um) max_permiss_val determined from: https://www.frontiersin.org/articles/10.3389/fmars.2021.658233/full#:~:text=Most%20studies%20targeted%20one%20specific%20size%20fraction%2C%20while,Massana%20et%20al.%2C%202015%3B%20Ramond%20et%20al.%2C%202019%29.

**Comment by jakjonbodc** [comment]
Created the following P01 terms:

DMMD2141 - Diameter median of eukaryote picophytoplankton in the water body by size fractionation and flow cytometry

DMMD7969 - Diameter median of nanoeukaryotic cells [Subgroup: autotrophic] in the water body by size fractionation and flow cytometry

P539DMMD - Diameter median of bacteria (ITIS: 202421: WoRMS 6) [Subgroup: heterotrophic] in the water body by size fractionation and flow cytometry

P700DMMD - Diameter median of Synechococcus (ITIS: 773: WoRMS 160572) in the water body by size fractionation and flow cytometry

P701DMMD - Diameter median of Prochlorococcus (ITIS: 610076: WoRMS 345515) in the water body by size fractionation and flow cytometry
