### ISSUE TITLE
Request for new P01 term related to seabed geomorphology (BODCNVS-1812)

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/P01#215]
<p><b>Term name (PrefLabel)</b><p>Location (geographic coordinates) of seabed geomorphological feature by classification to a term from Nanson et al. (2023). <p><b>Definition</b><p> The geographical location of a seabed geomorphological feature that has been classified using the Nansen et al. (2023) Classification Framework and Glossary - Version 1.0, published at https://doi.org/10.5281/zenodo.7804019.<p>

**Comment by roswri** [comment]
Term created and live on NVS:
http://vocab.nerc.ac.uk/collection/P01/current/MSPGLGP1/
