### ISSUE TITLE
Corrections to biological entities

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#219]
The following 3 codes have been updated following corrections to the biological entity component:
NA15S00Z	Abundance of Anemone (ITIS: 18425) per unit area of the bed by sieving and picking under an optical microscope	Abundance of Anemonia (WoRMS 100695) per unit area of the bed by sieving and picking under an optical microscope
ASP09441	Abundance of Spinocalanus (ITIS: 85390: WoRMS 104173) [Stage: adult Sex: male] per unit volume of the water body	Abundance of Spinocalanus (ITIS: 85390: WoRMS 104236) [Stage: adult Sex: male] per unit volume of the water body
ACA09366	Abundance of Calanidae (ITIS: 85259: WoRMS 10479) [Stage: adult Sex: female] per unit volume of the water body	Abundance of Calanidae (ITIS: 85259: WoRMS 104079) [Stage: adult Sex: female] per unit volume of the water body

Queued for publication on the NVS.

**Comment by danibodc** [comment]
Updates are live on the NVS.
