### ISSUE TITLE
NTR: concentration of DNA adducts in biota (BODCNVS-1863)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#226]
New P01 code needed for the alignment of Sandre/Quadrige terms with NVS P01 as part of Ifremer-SIMM contract.

Requires new record in chemical substance vocab S27 for [DNA adducts](https://en.wikipedia.org/wiki/DNA_adduct) and new units in P06 for (Nanomoles per mole).

**Comment by danibodc** [comment]
New S27 is live for DNA adducts:
https://vocab.nerc.ac.uk/collection/S27/current/CS004474/

New P06 is live for nanomoles per mole:
http://vocab.nerc.ac.uk/collection/P06/current/NMPM
