### ISSUE TITLE
Map Q01 to P01 [BODCNVS-2102]

### ISSUE THREAD

**Issue by EliLawrence** [nvs-vocabs/P01#227]
Following discussion with the OBIS vocabulary team, the following Q01 terms need to be mapped to new P01 codes @gwemon 

- [x] [Lower filter pore size](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100011)
- [x] [Sampling device aperture width](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100013)
- [x] [Biological sample size range](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100009)
- [x] [Sample extraction method](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100005)
- [x] [Sampling method](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100003)
- [x] [Upper sieve mesh size](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100008)
- [x] [Sampling device aperture surface area](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100017)
- [x] [Sampling net mesh size](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100015)
- [x] [Upper filter pore size](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100010)
- [x] [Lower sieve mesh size](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100007)
- [x] [Sampling instrument name](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100002)
- [x] [Sample preservation method](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100004)
- [x] [Subsampling protocol](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100006)
- [x] [Sampling device aperture length](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100014)
- [x] [Sampling platform name](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100001)
- [ ] ~[Sampling instrument efficiency](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100016)~ (deprecated)
- [x] [Sampling device aperture diameter](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100012)

Then they can be deprecated. Thanks!

**Comment by gwemon** [comment]
[Q0100001](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100001) becomes Name of sampling platform	in P01 with definition:  The name of the platform used to make the sampling, measurement or observation.
using existing S06 [Name](http://vocab.nerc.ac.uk/collection/S06/current/S0600157/)  and new S29 term	"sampling platform" defined as: A structure or vehicle that serves as a base for deploying sampling or sensing equipment.	

[Q0100002](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100002) becomes Name of sampling instrument in P01 with definition:	The name of the gear or instrument used to collect the sample or make the in-situ measurement or observation.
Re-uses 	[Name](http://vocab.nerc.ac.uk/collection/S06/current/S0600157/)	and needs new S29 term "sampling instrument" defined as	Equipment designed to collect physical samples.	

[Q0100003](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100003)	becomes	Description of sampling method in P01 with definition:	Text describing the method used to collect the sample or make the in-situ measurement or observation.
Re-uses [Description](http://vocab.nerc.ac.uk/collection/S06/current/S0600147/) and requires new S29 for	"sampling method" defined as	Method used to obtain the samples used for the analysis.

[Q0100004](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100004)	becomes Description of sample preservation method in P01 with definition:	Text describing the method used to preserve the sample after collection and prior to the analysis.
Re-uses [Description](http://vocab.nerc.ac.uk/collection/S06/current/S0600147/)	and requires new S29 for "sample preservation method"	Method used to preserve the samples after collection and prior to analysis.	

[Q0100005](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100005)	becomes Description of sample extraction method in P01 with defintion:	Text describing the method used to extract the biological material from its surrounding matrix.
Re-uses [Description](http://vocab.nerc.ac.uk/collection/S06/current/S0600147/) and requires new S29 term for	"sampling extraction method" with defintion:	Method used to extract the analysed sample from its matrix.	

[Q0100006](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100006)	becomes Description of sub-sampling protocol in P01 with defintion:	Text describing the method used to divide the sample into subsamples.
Re-uses: [Description](http://vocab.nerc.ac.uk/collection/S06/current/S0600147/)	and requires new "sub-sampling protocol"	defined as Method used to divide the sample into sub-samples	

[Q0100007](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100007)	becomes Size of sampling processor (lower mesh) in P01 with defintion:	The mesh size of the sieve used to sort biological material from a sample (typically a sediment sample). Only the material that remains in the sieve is used in the analyses.
Re-uses: [Size](http://vocab.nerc.ac.uk/collection/S06/current/S0600023/)	and requires new S29 for "sampling processor (lower sieve)"	Equipment used to sort biological or geological material. Only the material that remains on the sieve is used in the analyses.	

[Q0100008](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100008)	becomes Size of sampling processor (upper mesh) in P01 with defintion: 	The mesh size of the sieve used to sort biological material from a sample (typically a sediment sample). The material that remains in the sieve is discarded.
Re-uses: [Size](http://vocab.nerc.ac.uk/collection/S06/current/S0600023/)	requires new S29 for "sampling processor (upper sieve)"	Equipment used to sort biological or geological material. The material that remain on the sieve is discarded.	

[Q0100009](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100009)	becomes Size class of analysed biological entities in P01 with defintion:	The size class of the biological entities used for the observation. Specimens with sizes outside this range would not be included in the dataset.
Reuses [Size class](http://vocab.nerc.ac.uk/collection/S06/current/S0600089/) and requires new S29 for	"analysed biological entities" with defintion	The biological organisms used in the analysis.

**Comment by gwemon** [comment]
Unformatted content dumped here for the time being - will reformat later to make it more readable.

[Q0100010](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100010)	Size	sampling processor (upper filter pore)	Equipment used to remove particulate material that is retained on the filter from a liquid or gas sample. Only the material and liquid passing through the filter are used in the analysis.	Size of sampling processor (upper filter pore)	The pore size of the filter used to exclude particulate material from a sample (typically a water sample). Only the material and liquid passing through the filter are used in the analysis.
[Q0100011](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100011)	Size	sampling processor (lower filter pore)	Equipment used to collect particulate material from a liquid or gas sample. Only the material collected on the filter is used in the analysis.	Size of sampling processor (lower filter pore)	The pore size of the filter used to collect particulate material from a sample (typically a water sample). Only the material collected on the filter is used in the analysis.
[Q0100012](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100012)	[Diameter](http://vocab.nerc.ac.uk/collection/S06/current/S0600211/)	[sample collector (aperture)](http://vocab.nerc.ac.uk/collection/S29/current/PE001236)		Diameter of sample collector (aperture)	The diameter of the sampling area of a device with a circular aperture (e.g. a corer or a net); the type of device is specified elsewhere.
[Q0100013](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100013)	[Width](http://vocab.nerc.ac.uk/collection/S06/current/S0600155/)	[sample collector (aperture)](http://vocab.nerc.ac.uk/collection/S29/current/PE001236)		Width of sample collector (aperture)	The smaller dimension of the sampling area of a device with a rectangular aperture (e.g. a grab or a trawl); the type of device is specified elsewhere.
[Q0100017](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100017)	[Area](http://vocab.nerc.ac.uk/collection/S06/current/S0600146/)	[sample collector (aperture)](http://vocab.nerc.ac.uk/collection/S29/current/PE001236)		Area of sample collector (aperture)	The 2-dimensional size of the opening of a sampling device (e.g. a grab or a trawl); the type of device is specified elsewhere
[Q0100014](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100014)	[Length](http://vocab.nerc.ac.uk/collection/S06/current/S0600015/)	[sample collector (aperture)](http://vocab.nerc.ac.uk/collection/S29/current/PE001236)		Length of sample collector (aperture)	The larger dimension of the sampling area of a device with a rectangular aperture (e.g. a grab); the type of device is specified elsewhere.
[Q0100015](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100015)	[Size](http://vocab.nerc.ac.uk/collection/S06/current/S0600023/)	[sample collector (mesh)](http://vocab.nerc.ac.uk/collection/S29/current/PE001237)		Size of sample collector (mesh)	The average dimension of the holes in the mesh of a sample collecting device such as a plankton net or a trawl.
[Q0100016](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100016)	??	sampling instrument or method?		??	??

**Comment by gwemon** [comment]
Please review the suggested terms above and provide help with defining what this refers to: 
[Q0100016](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100016)	??	sampling instrument or method?		??	??

**Comment by ssmosstee** [comment]
Good Question about the [Q0100016](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100016/) term. I think one could define it either way.  My first thought (when looking at the decision tree) is to allocate it to the method since it is higher up in the tree of decisions to make). Would something like this fit into a vocabulary like [G05](https://vocab.nerc.ac.uk/collection/G05/current/)? But of course that falls outside of S06 or S29...

But now that I think about it more, the measurement of efficiency will only ever belong to the instrument that it was calculated for (since there might be more variation between individual instruments). Maybe placing the attribution under the instrument is better.

I can't speak much to the other re-mappings other than saying they all look good to me.

**Comment by gwemon** [comment]
Following OBIS Vocab Team meeting of 15 Nov 2023 decision is to deprecate http://vocab.nerc.ac.uk/collection/Q01/current/Q0100016/ as this term is hard to define and it has never used in OBIS.

**Comment by gwemon** [comment]
I am keen to deprecate the concept "Size" in S06 (http://vocab.nerc.ac.uk/collection/S06/current/S0600023/) because most of the time we should use more precise terms like e.g. length, diameter, width, height, etc... When used, "size" should always be qualified i.e. "grain-size". We already have created a term for "Grain-size" in S06 (http://vocab.nerc.ac.uk/collection/S06/current/S0600192/). So I am proposing to create a similar term for "Mesh size".

**Comment by gwemon** [comment]
Sorry I forgot to acknowledge your comment @ssmosstee and suggestion about G05. Just to ighlight that G05 is an ISO vocabulary so we would definitely not add to it. Just for info.

**Comment by gwemon** [comment]
With the decision of not using Size but instead creating a Mesh size term in S06 the following Q01 codes would be modelled as follows in the PUV model:
[Q0100007](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100007)
P01 Preferred Label: Mesh size of sampling processor (lower sieve)
Definition: The average one-dimensional mesh aperture size of the sieve used to sort biological material from a sample (typically a sediment sample). Only the material that remains in the sieve is used in the analyses.
Requires new S06 and new S29 for "sampling processor (lower sieve)" Equipment used to sort biological or geological material. Only the material that remains on the sieve is used in the analyses.

[Q0100008](http://vocab.nerc.ac.uk/collection/Q01/current/Q0100008)
P01 Preferred Label: Mesh size of sampling processor (upper mesh)
Definition: The average one-dimensional aperture mesh size of the sieve used to sort biological material from a sample (typically a sediment sample). The material that remains in the sieve is discarded.

Requires new S06 and new S29 for "sampling processor (upper sieve)" Equipment used to sort biological or geological material. The material that remain on the sieve is discarded.

**Comment by jakjonbodc** [comment]
Created new S29 terms:
sampling instrument - https://vocab.nerc.ac.uk/collection/S29/current/PE001512/
sampling method - https://vocab.nerc.ac.uk/collection/S29/current/PE001513/
sampling platform - https://vocab.nerc.ac.uk/collection/S29/current/PE001511/
sample preservation method - https://vocab.nerc.ac.uk/collection/S29/current/PE001514/
sub-sampling protocol - https://vocab.nerc.ac.uk/collection/S29/current/PE001516/
sample extraction method - https://vocab.nerc.ac.uk/collection/S29/current/PE001515/

**Comment by jakjonbodc** [comment]
Created new P01 terms:
Name of sampling instrument - http://vocab.nerc.ac.uk/collection/P01/current/NMSPINST/
Name of sampling platform - https://vocab.nerc.ac.uk/collection/P01/current/NMSPPF01/
Description of sub-sampling protocol - https://vocab.nerc.ac.uk/collection/P01/current/DSPSSP01/
Description of sample extraction method - https://vocab.nerc.ac.uk/collection/P01/current/DSSPXTMT/
Description of sample preservation method - https://vocab.nerc.ac.uk/collection/P01/current/DSSPPRMT/
Description of sampling method - https://vocab.nerc.ac.uk/collection/P01/current/DSSPMT01/

**Comment by jakjonbodc** [comment]
Created new S29 terms:
analysed biological entities - https://vocab.nerc.ac.uk/collection/S29/current/PE001518/
sampling processor (upper filter) - https://vocab.nerc.ac.uk/collection/S29/current/PE001519/
sampling processor (lower sieve) - https://vocab.nerc.ac.uk/collection/S29/current/PE001520/
sampling processor (upper sieve) - https://vocab.nerc.ac.uk/collection/S29/current/PE001521/

**Comment by jakjonbodc** [comment]
Created the following P01 terms:
Mesh size of sampling processor (lower sieve) - https://vocab.nerc.ac.uk/collection/P01/current/MSHSIZE2/
Mesh size of sampling processor (upper sieve) - https://vocab.nerc.ac.uk/collection/P01/current/MSHSIZE3/
Size class of analysed biological entities - https://vocab.nerc.ac.uk/collection/P01/current/SZCLBIO1/
Diameter of sample collector (aperture) - https://vocab.nerc.ac.uk/collection/P01/current/DSAMPA01/

Updated definitions of the following existing terms to as specified above:
Area of sample collector (aperture) {mouth area} - https://vocab.nerc.ac.uk/collection/P01/current/MTHAREA1/
Height of sample collector (aperture) {mouth height} - https://vocab.nerc.ac.uk/collection/P01/current/MTHHGHT1/
Width of sample collector (aperture) {mouth width} - https://vocab.nerc.ac.uk/collection/P01/current/MTHWDTH1/

**Comment by jakjonbodc** [comment]
updated https://vocab.nerc.ac.uk/collection/P01/current/DSAMPA01/ to link to https://vocab.nerc.ac.uk/collection/P02/current/SAMP/ as this is a more appropriate parameter group code.

**Comment by EliLawrence** [comment]
Thanks for your work on this @jakjonbodc! I see the lower and upper filter pore size were checked off, but I don't see a P01 link to those ones. Would you mind sharing those links?

**Comment by jakjonbodc** [comment]
Created new P01's:

Pore size of sampling processor (upper filter) - http://vocab.nerc.ac.uk/collection/P01/current/PRSZSPUP/
Pore size of sampling processor (lower filter) - http://vocab.nerc.ac.uk/collection/P01/current/PRSZSPLW/

New S29:

sampling processor (lower filter) - http://vocab.nerc.ac.uk/collection/S29/current/PE001522/

**Comment by jakjonbodc** [comment]
You're welcome! Please find the remaining terms above and do get in touch if there are any issues.

**Comment by EliLawrence** [comment]
Thanks again! Now that all the terms are mapped to P01, could we deprecate the Q01 terms? 
I was also wondering when, if you know, these new terms will be available through the SeaDataNet P01 Facet search? I don't see them appear through that search interface yet.

**Comment by gwemon** [comment]
@EliLawrence The issue with the SeaDataNet P01 Facet Search has been fixed by our colleagues at MARIS. We should now expect the Facet search to return the same results as the BODC search app. Any issues please contact us.

**Comment by EliLawrence** [comment]
That's great, thanks Gwen! No issues so far

**Comment by gwemon** [comment]
Will look at this on Monday @EliLawrence

**Comment by gwemon** [comment]
> After investigating some more, it seems the four terms below don't belong to the P02 "sampling parameters" but instead are "metadata parameters". Is it possible to map these to sampling parameters so all these old Q01 terms are in the same P02 group "sampling parameters"? It'll definitely make it easier for us developing training on how to find these if it's in one group.
> 
> [Size class of analysed biological entities](https://vocab.nerc.ac.uk/collection/P01/current/SZCLBIO1/) [Mesh size of sampling processor (upper sieve)](https://vocab.nerc.ac.uk/collection/P01/current/MSHSIZE3/) [Mesh size of sample collector](http://vocab.nerc.ac.uk/collection/P01/current/MSHSIZE1/) [Mesh size of sampling processor (lower sieve)](https://vocab.nerc.ac.uk/collection/P01/current/MSHSIZE2/)
> 
> Thanks!

@EliLawrence Changes made in our database and queued for overnight publication on the NVS.

**Comment by EliLawrence** [comment]
Fantastic, thank you Gwen!
