### ISSUE TITLE
NTR Identifier of sampling station [BODCNVS-1930]

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#229]
Reuses: http://vocab.nerc.ac.uk/collection/S06/current/S0600156/
Requires new S29: sampling station with proposed definition: A location at which measurements or samples were taken.

**Comment by ahpanton** [comment]
New P01 code created:

IDSMST01 Identifier of sampling station - the identifier of a location or facility at which measurements or samples were taken

**Comment by ahpanton** [comment]
P01 now active

[IDSMST01](http://vocab.nerc.ac.uk/collection/P01/current/IDSMST01/) Identifier of sampling station - the identifier of a location or facility at which measurements or samples were taken
