### ISSUE TITLE
NTR for vertical beam variables from Teledyne RDI Sentinel V ADCP

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#23]
BODCNVS-350 "I have a raw ADCP file from a Teledyne RDI Sentinel V instrument, which contains variables for vertical beam velocity (vv), vertical beam amplitude (va), vertical beam percent good (vg) and vertical beam correlation magnitude (vq). I am writing to request P01 codes for these variables, to be included in the definitions of those variables in a netCDF file exported from the raw file."

**Comment by gwemon** [comment]
Following discussion with the requester, the variables have been remodelled as follows based on the P01 semantic model:

Vertical correlation magnitude:
Correlation magnitude of acoustic signal returns from the water body by acoustic doppler current profiler (ADCP) vertical beam

Vertical beam amplitude:
Amplitude of acoustic signal returns from the water body by acoustic doppler current profiler (ADCP) vertical beam

Vertical Percent good:
Acceptable proportion of acoustic signal returns from the water body by acoustic doppler current profiler (ADCP) vertical beam

Vertical beam velocity:
Upward velocity of acoustic signal returns from the water body by acoustic doppler current profiler (ADCP) vertical beam

**Comment by danibodc** [comment]
The following have now been published on the NVS:

Upward velocity of acoustic signal returns from the water body by acoustic doppler current profiler (ADCP) vertical beam
http://vocab.nerc.ac.uk/collection/P01/current/LRZUVP01/

Amplitude of acoustic signal returns from the water body by acoustic doppler current profiler (ADCP) vertical beam
http://vocab.nerc.ac.uk/collection/P01/current/ASAMAP05/

Acceptable proportion of acoustic signal returns from the water body by acoustic doppler current profiler (ADCP) vertical beam
http://vocab.nerc.ac.uk/collection/P01/current/PCGDAP05/

Correlation magnitude of acoustic signal returns from the water body by acoustic doppler current profiler (ADCP) vertical beam
http://vocab.nerc.ac.uk/collection/P01/current/CMAGZZ05/
