### ISSUE TITLE
P01 codes for total nitrogen in sediments using the Kjeldahl and dry combustion aka "elemental analysis" methods

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#233]
Required for alignment of Sandre/Quadrige and NVS vocabularies (SIMM project)

Proposing to use [Concentration of total nitrogen {total_N} per unit dry weight of sediment <2000um](http://vocab.nerc.ac.uk/collection/P01/current/MAMR0051/) as a template, create:

For the Kjeldahl method:
For the <2000um sediment fraction:
Concentration of total nitrogen {total_N} per unit dry weight of sediment <2000um by Kjeldahl method using https://vocab.nerc.ac.uk/collection/S04/current/S0501/ from the S04 collection
and also for bulk sediment:
Concentration of total nitrogen {total_N} per unit dry weight of sediment by Kjeldahl method

for the dry combustion method (related to [ISO ](https://www.iso.org/obp/ui/en/#iso:std:iso:13878:en))
Concentration of total nitrogen {total_N} per unit dry weight of sediment <2000um by elemental analysis http://vocab.nerc.ac.uk/collection/S04/current/S041/
and also for bulk sediment:
Concentration of total nitrogen {total_N} per unit dry weight of sediment by elemental analysis

**Comment by jakjonbodc** [comment]
Created the below terms:

MAKJ0051 - Concentration of total nitrogen {total_N} per unit dry weight of sediment <2000um by Kjeldahl method
https://vocab.nerc.ac.uk/collection/P01/current/MAKJ0051/

MAEA0051 - Concentration of total nitrogen {total_N} per unit dry weight of sediment <2000um by elemental analysis
https://vocab.nerc.ac.uk/collection/P01/current/MAEA0051/

MAEABU51 - Concentration of total nitrogen {total_N} per unit dry weight of sediment by Kjeldahl method
https://vocab.nerc.ac.uk/collection/P01/current/MAEABU51/

MABUEA51 - Concentration of total nitrogen {total_N} per unit dry weight of sediment by elemental analysis
https://vocab.nerc.ac.uk/collection/P01/current/MABUEA51/
