### ISSUE TITLE
P01 codes request - to replace unaccepted taxon names/incorrect biological entities [BODCNVS-2314]

### ISSUE THREAD

**Issue by jakjonbodc** [nvs-vocabs/P01#263]
Request received to review/create P01 codes for 9 concepts. 

5 proposed concepts with biological entities that replace unaccepted taxon names according to WoRMS.
For example,
the concept < Abundance of Heterorhabdus robustus (WoRMS 104581) [Stage: adult Sex: female] per unit volume of the water body >, code AHE09370<[http://vocab.nerc.ac.uk/collection/P01/current/AHE09370/&gt;,](http://vocab.nerc.ac.uk/collection/P01/current/AHE09370/%3E,) contains the biological entity 'Heterorhabdus robustus (WoRMS 104581)', which is now an unaccepted name replaced by 'Paraheterorhabdus robustus (WoRMS 368129)'.
The proposed term is:
< Abundance of Paraheterorhabdus robustus (WoRMS 368129) [Stage: adult Sex: female] per unit volume of the water body>.

4 proposed concepts containing biological entities that should replace an incorrect biological entity (taxon in a different phylum!).
For example,
The concept < Abundance of Metridiidae (WoRMS 100678) [Stage: copepodites C3] per unit volume of the water body>, code AME09389<[http://vocab.nerc.ac.uk/collection/P01/current/AME09389/&gt;,](http://vocab.nerc.ac.uk/collection/P01/current/AME09389/%3E,) contains the biological entity 'Metridiidae (WoRMS 100678)', which is a sea anemone referring to the copepod developmental stage! It should have the biological entity 'Metridinidae (WoRMS 104092)'.
The proposed term is:
< Abundance of Metridinidae (WoRMS 104092) [Stage: copepodites C3] per unit volume of the water body>.

Proposed terms:

Abundance of Paraheterorhabdus robustus (WoRMS 368129) [stage: adult sex: female] per unit volume of the water body
Abundance of Metridinidae (WoRMS 104092) [stage: copepodites C3] per unit volume of the water body
Abundance of Metridinidae (WoRMS 104092) [stage: nauplii] per unit volume of the water body
Abundance of Metridinidae (WoRMS 104092) [stage: copepodites C1] per unit volume of the water body
Abundance of Metridinidae (WoRMS 104092) [stage: copepodites C2] per unit volume of the water body
Abundance of Lampanyctus achirus (WoRMS 217707) [stage: not specified] per unit volume of the water body
Abundance of Hansarsia megalops (WoRMS 1649789) [stage: not specified] per unit volume of the water body
Abundance of Stomias boa (WoRMS 127374) [stage: not specified] per unit volume of the water body
Abundance of Tectipleura (WoRMS 1057250) [stage: not specified] per unit volume of the water body

**Comment by ahpanton** [comment]
S25 corrections for 4 x Metridiidae terms completed - new taxon name Metridinidae, AphiaID 104092
P01s related to these terms updated - same P01 codes as before:
AME09442	Abundance of Metridinidae (WoRMS 104092) [Stage: copepodites C2] per unit volume of the water body	
AME09425	Abundance of Metridinidae (WoRMS 104092) [Stage: nauplii] per unit volume of the water body	
AME09408	Abundance of Metridinidae (WoRMS 104092) [Stage: copepodites C1] per unit volume of the water body	
AME09389	Abundance of Metridinidae (WoRMS 104092) [Stage: copepodites C3] per unit volume of the water body	

Five new S25s created:
BE010390	Tectipleura (WoRMS 1057250)
BE010389	Stomias boa (ITIS: 162292: WoRMS 127374)
BE010388	Hansarsia megalops (WoRMS 1649789)
BE010387	Paraheterorhabdus robustus (ITIS: 667263: WoRMS 368129) [Stage: adult Sex: female]
BE010386	Lampanyctus achirus (ITIS: 182881: WoRMS 217707)

Five new P01s created for these new S25s:
TEC10390	Abundance of Tectipleura (WoRMS 1057250) per unit volume of the water body	
STO10389	Abundance of Stomias boa (ITIS: 162292: WoRMS 127374) per unit volume of the water body	
LAM10386	Abundance of Lampanyctus achirus (ITIS: 182881: WoRMS 217707) per unit volume of the water body	
HAN10388	Abundance of Hansarsia megalops (WoRMS 1649789) per unit volume of the water body	
PAR10387	Abundance of Paraheterorhabdus robustus (ITIS: 667263: WoRMS 368129) [Stage: adult Sex: female] per unit volume of the water body

Description discussed with originator - 'Number of individuals from the specified biological entity identified, counted and normalised to a unit volume of water sample.'

Terms will be available online on the NVS from tomorrow morning

**Comment by ahpanton** [comment]
Links for the 5 new P01s now live:

[TEC10390](http://vocab.nerc.ac.uk/collection/P01/current/TEC10390/) Abundance of Tectipleura (WoRMS 1057250) per unit volume of the water body
[STO10389](http://vocab.nerc.ac.uk/collection/P01/current/STO10389/) Abundance of Stomias boa (ITIS: 162292: WoRMS 127374) per unit volume of the water body
[LAM10386](http://vocab.nerc.ac.uk/collection/P01/current/LAM10386/) Abundance of Lampanyctus achirus (ITIS: 182881: WoRMS 217707) per unit volume of the water body
[HAN10388](http://vocab.nerc.ac.uk/collection/P01/current/HAN10388/) Abundance of Hansarsia megalops (WoRMS 1649789) per unit volume of the water body
[PAR10387](http://vocab.nerc.ac.uk/collection/P01/current/PAR10387/) Abundance of Paraheterorhabdus robustus (ITIS: 667263: WoRMS 368129) [Stage: adult Sex: female] per unit volume of the water body
