### ISSUE TITLE
OG1:TCPUCHLA  Same As  P01: TCNTICPU possible bad linkage [BODCNVS-2383]

### ISSUE THREAD

**Issue by callumrollo** [nvs-vocabs/P01#271]
Crossover vocabularies Issue

**Motivation**: We have a variable that represents the internal temperature of a PAR sensor. We need to reference the correct OG1 concept for this variable.

**Issue description** OG1 has the concept [OG1:TCPUCHLA](https://vocab.nerc.ac.uk/collection/OG1/current/TCPUCHLA/) with the label "Thermistor signal from backscattering sensor". The label and concept name, which includes CHLA, indicate that this concept is solely for the internal temperature of backscattering/CHLA sensors. However, OG1:TCPUCHLA has the linkage "Same As" to [P01:TCNTICPU](https://vocab.nerc.ac.uk/collection/P01/current/TCNTICPU/).  P01: TCNTICPU has the label "Raw signal (counts) of CPU temperature determination" and the Definition "The raw analogue-to-digital converter output from a temperature sensor mounted on a CPU that is a component part of an instrument or sensor.". This suggests to me that we can use P01: TCNTICPU for the internal temperature of our PAR sensor, as it covers broadly instruments and sensors.

**Questions**

1. Can we use OG1:TCPUCHLA as the reference concept for the internal temperature of a PAR sensor, despite it specifying "backscattering sensor"? Or should we use P01: TCNTICPU? Or do we request a new OG1 term?
2. Is it the case that P01: TCNTICPU is "Same As" OG1:TCPUCHLA, given that the latter is textually more restrictive (flourometers only)?
3. If so, how flexible is the "Same As" linkage? 

This Issue has been crossposted to OG1 https://github.com/OceanGlidersCommunity/OG-format-user-manual/issues/263

**Comment by danibodc** [comment]
Discussion in progress at https://github.com/OceanGlidersCommunity/OG-format-user-manual/issues/263
