### ISSUE TITLE
NTR BODCNVS-641: Coralligenous parameters

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#35]
We have received a request for the creation of 3 parameters related to coralligenous habitats
The first two parameters :
* . perc_colo_big_100mm_height -> Percentage of colonies equal or larger than 100 mm in height in the studied population (range 0 to 100%).
* . perc_colo_big_7mm_diameter -> Percentage of colonies equal or larger than 7 mm in diameter in the studied population (range 0 to 100%).
are related only to the red coral Corallium rubrum, since they are parameters to evaluate its conservation status and the lack of poaching impact
 
The other one:
* . perc_affected_colo -> Percentage of colonies affected by at least 10% of necrosis.
can be used with all gorgonian species and the bryozoans, so can be related to an habitat of multi-specificic assemblages, in this case coralligenous

**Comment by gwemon** [comment]
For  perc_colo_big_7mm_diameter, I am proposing to model it using the biological variant of the P01 semantic model, as follows:
- PrefLabel: "**Proportion of Corallium rubrum colonies (ITIS: 202513: WoRMS 125416) [Size: diameter >= 7mm]**"
where:
- "Proportion" is the property observed
- "Corallium rubrum colonies diameter>=7mm" is the object of interest

- This new P01 code will be linked to unit=percent (http://vocab.nerc.ac.uk/collection/P06/current/UPCT/)

-  Proposed definition: 
"Number of colonies from the specified species with a diameter equal to or greater than the specified threshold, expressed as a proportion relative to the total number of colonies of that same species observed in the surveyed population. Generally expressed as a percentage, this is a parameter used to evaluate the conservation status of the targetted biological species and assess the impact of poaching."

Note that this modelling is not ideal because some elements are implied but this is a common problem for terms that are expressed as a proportion of something, at least in the P01 semantic model as it stands. The proportion of what is generally assumed and not expressed. We may, in the future be able to improve this for machine readability but, for the time being, this is the best we can do without confusing the user. The detailed definition should ensure that the term is at least unambiguous to human users.

**Comment by gwemon** [comment]
Based on the example above, the modelling of "perc_colo_big_100mm_height" will be:

PrefLabel: "Proportion of Corallium rubrum colonies (ITIS: 202513: WoRMS 125416) [Size: height >= 100mm]"
where:

"Proportion" is the property observed

"Corallium rubrum colonies height >=100mm" is the object of interest

unit=percent (http://vocab.nerc.ac.uk/collection/P06/current/UPCT/)

Proposed definition:
"Number of colonies of the specified species with a height equal to or greater than the specified threshold, expressed as a proportion relative to the total number of colonies of that same species observed in the surveyed population. Generally expressed as a percentage, this is a parameter used to evaluate the conservation status of the targetted biological species and assess the impact of poaching."

**Comment by gwemon** [comment]
The last parameter: perc_affected_colo could be modelled as follows:
- Preferred label: **Proportion of coralligenous colonies [Sub-group: with percentage necrosis >=10%]**
- Definition: Number of coralligenous colonies (that is multi-species assemblages made of gorgonian and bryozoan species) with a percentage of necrosis equal to or greater than 10% of the living area of the colony, and expressed as a proportion relative to the total number of colonies observed in the surveyed population. Generally expressed as a percentage, this is a parameter used to evaluate the conservation status of the coralligenous habitats.

**Comment by gwemon** [comment]
If we can confirm that this is indeed proportion by number then we could use [this S06 term](http://vocab.nerc.ac.uk/collection/S06/current/S0600070/) instead of just "Proportion".

**Comment by lfiguerolaferrando** [comment]
Thank you for all your work! 

Regarding the last parameter “perc_affected_colo” we would add two remarks:

**1) Measurement unit**
The measurement unit of “perc_affected_colo” should be the same as the other two parameters (“perc_colo_big_100mm_height”, and “perc_colo_big_7mm_diameter”) in order to fit the data as much as possible. As it is a percentage, it would be better to use just “Proportion”. It would be possible?

**2) Definition:** 
•	It should say: Number of coralligenous colonies (that is multi-species assemblages made of gorgonian, **coral, sponge**, and bryozoan species)”….
•	Instead of “Number of coralligenous colonies (that is multi-species assemblages made of gorgonian and bryozoan species)”….

The other parameters are very well described, thank you! 
Do not hesitate to contact us to resolve any other questions.

**Comment by gwemon** [comment]
Thank you @lfiguerolaferrando for your feedback. My intention was to apply "Proportion by number" to all 3 new parameters if this was more appropriate but I am fine with just "Proportion" and the definitions as they stand taking into account your suggestions.

**Comment by gwemon** [comment]
@lfiguerolaferrando 
The three new P01 codes have now been published on the NVS:
http://vocab.nerc.ac.uk/collection/P01/current/PCCRDI01/
http://vocab.nerc.ac.uk/collection/P01/current/PCCRHT01/
http://vocab.nerc.ac.uk/collection/P01/current/PCRCNC10/
Any issues, please let us know by reopening this ticket.

**Comment by lfiguerolaferrando** [comment]
Thank you @gwemon for all the work and for introducing these terms.
We really appreciate it!
Keep regards.

Missatge de Gwen Moncoiffé <notifications@github.com> del dia dg., 18
d’oct. 2020 a les 21:45:
