### ISSUE TITLE
NTR: Biomass as nitrogen of Macroalgae per unit area of the sea surface

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P01#43]
Symbol: **MA**

Units: **g.m-2**

Definition: Concentration of nitrogen biomass per m<sup>2</sup> of macrolagae. Macroalgae (or seaweed) grows above all other benthic plants (corals, seagrasses, benthic microalgae). It is parameterised as a non-calcifying leafy algae, with a C:N:P ratio of 550:30:1, and a formulation for calculating the percentage of the bottom covered as 1-exp(-&Omega;<sub>MA</sub> _MA_). In the model, in the absence of both calcifying macroalgae (particularly _Halimeda_) and unicellular epiphytes, macroalgae represents the biomass of all seaweeds and epiphytes.

Source: https://doi.org/10.5194/gmd-13-4503-2020 **Supplement** _Table 7_ https://gmd.copernicus.org/articles/13/4503/2020/gmd-13-4503-2020-supplement.zip

**Comment by dr-shorthair** [comment]
Will this need a _macroalgae_ entity to be added to S25?

**Comment by gwemon** [comment]
Proposing to model this new P01 term as:
Property (S06) = Biomass as nitrogen
Target object (S25) = macroalgae
Matrix (S26) = water body
Property-matrix relationship (S02) = per unit area of the

**Comment by gwemon** [comment]
This has been published as:
https://vocab.nerc.ac.uk/collection/P01/current/NB9624MO/
as part of the eReefs project.
