### ISSUE TITLE
NTR: Biomass as nitrogen of Zostera per unit area of the sea surface

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P01#44]
Symbol: **SG**

Units: **g.m-2**

Definition: Concentration of nitrogen biomass per m<sup>2</sup> of a seagrass form parameterised to be similar to _Zostera_. This form captures light after it has passed through macroalgae and before it passes through _Halophila_. This form is better adapted to high light, low nutrient conditions than _Halophila_ as a result of a deeper root structure and being able to shade it. See macroalgae for elemental ratio and bottom cover.

Source: https://doi.org/10.5194/gmd-13-4503-2020 **Supplement** _Table 7_ https://gmd.copernicus.org/articles/13/4503/2020/gmd-13-4503-2020-supplement.zip

**Comment by dr-shorthair** [comment]
I see [Zostera marina](http://vocab.nerc.ac.uk/collection/S25/current/BE007962/) in S25, but I think we need the genus to support this case.

**Comment by gwemon** [comment]
This has been published as:
http://vocab.nerc.ac.uk/collection/P01/current/NB9622MO
As part of the eReefs project
