### ISSUE TITLE
NTR: Biomass as nitrogen of Halophila per unit area of the sea surface

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P01#45]
Symbol: **SGH**

Units: **g.m-2**

Definition: Concentration of nitrogen biomass per m<sup>2</sup> of a seagrass form parameterised to be similar to _Halophila ovalis_. This form captures light after it has passed through the _Zostera_ seagrass form. The _Halophila ovalis_ form is better adapted to low light conditions than _Zostera_, having a faster growth rate and lower minimum light requirement. See macroalgae (MA) for elemental ratio and bottom cover.

Source: https://doi.org/10.5194/gmd-13-4503-2020 **Supplement** _Table 7_ https://gmd.copernicus.org/articles/13/4503/2020/gmd-13-4503-2020-supplement.zip

**Comment by dr-shorthair** [comment]
I suppose we need _Halophila ovalis_ added to S25 to support this?

**Comment by gwemon** [comment]
These have been published as:
https://vocab.nerc.ac.uk/collection/P01/current/NB9625MO/
http://vocab.nerc.ac.uk/collection/P01/current/NB9621MO/
as part of the eReefs project.
