### ISSUE TITLE
NTR: new code needed for Length maximum of Chamelea gallina and Ruditapes philippinarum (BODCNVS-781)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#48]
see https://github.com/nvs-vocabs/S25/issues/7

**Comment by danibodc** [comment]
The following P01 terms have now been created and are live on the NVS:

http://vocab.nerc.ac.uk/collection/P01/current/MXLN8957/
Length maximum of Chamelea gallina (ITIS: 205649: WoRMS 141907)

http://vocab.nerc.ac.uk/collection/P01/current/MXLN9243/
Length maximum of Ruditapes philippinarum (WoRMS 231750)
