### ISSUE TITLE
NTR for high frequency radar parameters - water current radial velocity, direction and standard error (BODCNVS-368)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#49]
Request for new P01 codes for surface current radial velocity, radial velocity standard error, and direction by high frequency radar.

**Comment by gwemon** [comment]
We are proposing to model the requested terms as:
#1 Radial velocity (away from) of water current relative to instrument in the water body by high frequency radar, where
Property (S06): Radial velocity (away from)
Target object / object of interest (S29): water current relative to instrument 
Matrix (S26): water body
Analytical / measurement method (S04): high frequency radar

Same as: http://vocab.nerc.ac.uk/collection/P07/current/CFV13N15/

#2 corresponding standard error
Radial velocity (away from) standard error of water current relative to instrument in the water body by high frequency radar

**Comment by bodcmahe** [comment]
A third term is also needed:

Direction (away from) of radial vector relative to instrument and True North in the water body by high frequency radar.

Target object / object of interest (S29): radial vector relative to instrument and True North

Same as: http://vocab.nerc.ac.uk/collection/P07/current/CFV13N5/

**Comment by roy-lowry** [comment]
One of those mental conundrums. A radial velocity can be fully described in different ways.

1) speed plus direction towards with direction negative if water moving away from sensor
2) speed plus direction away from with direction negative if water moving towards sensor
3) direction plus velocity towards with velocity negative if water moving away from sensor
4) direction plus velocity away from with velocity negative if water moving towards sensor

Data originator will have adopted one of these conventions and obviously the parameter codes have to match the convention used.

Does that help?

**Comment by bodcmahe** [comment]
@roy-lowry @gwemon 

Thanks Roy. 

The source variable names are 'radial sea water velocity away from instrument - m/s' and 'direction of radial velocity away from instrument - Degrees True'. I have also established from the originator that radial velocity is positive if away from instrument. So option 4 in your list by my reckoning. 

The terms are required for variables 'RDVA' and 'DRVA' captured in the SeaDataCloud HFR Deliverable (p37) - available via:
https://ec.europa.eu/research/participants/documents/downloadPublic?documentIds=080166e5c46f0f36&appId=PPGMS

Trying to align with the CF terms CFV13N15 and CFV13N5 too and use similar terminology.

Definitions of the underlying S29 components (S18 and S20) are the current hurdle, particularly the definition of 'radial vector' for S18, which we are proposing to use for the direction of radial velocity variable.  

Do you think we're on the right lines?

Thanks,
Mark

**Comment by gwemon** [comment]
@roy-lowry  @bodcmahe  and these are the CF Standard Name equivalents:
http://vocab.nerc.ac.uk/collection/P07/current/CFV13N5/
http://vocab.nerc.ac.uk/collection/P07/current/CFV13N15/

**Comment by roy-lowry** [comment]
I don't think 'towards' or 'away from' are strictly needed for the direction, but I guess belt and braces doesn't hurt. The only cost is that should we ever get a radial velocity towards the instrument then an additional P01 code would be needed for the direction, but that's pretty trivial.

What CF have done is to put the semantics ('sea water') into the velocity standard name and then have a more generic direction standard name that would be equally applicable to something like radial_wind_velocity_away_from_instrument. Following their lead would make sense.

As the years pass my mental map of the semantic model fades so I can be of limited help when it come to details. However, I have seen a definition of 'radial vector' that I quite like which is 'The linear polar co-ordinate of a vector measurement'.

One thought I was having is what about specification of a 3D radial velocity, but I think 'direction' specifies the horizontal plane, with a word like 'elevation' being a possible equivalent for the vertical plane.

This is a community using more precise terminology for something we've described loosely for years.  The early current meters measured a scalar speed (how fast a mechanical rotor turned) plus the orientation of a vane using a compass. The instrument design meant that compass always pointed in the direction the water was flowing so the speed was converted from a scalar into an 'away from' radial vector. However, the semantics never recognised this fact. Consequently, 'current speed' and 'radial sea water velocity away from' are de facto synonyms with the latter a more mathematically-correct description of the same thing as the former. Likewise with 'current direction' and 'direction of radial velocity'. Note I'm not suggesting pushing the HFR community into using the loose semantics of the past, but some sort of mapping (weaker than SameAs) might be appropriate.

Hope this helps.

**Comment by gwemon** [comment]
@roy-lowry I iked your suggestion to remove the towards/away from and just have
"Direction of radial vector relative to instrument and True North in the water body by high frequency radar"
however that would mean creating a new S06 term which could then potentially be mis-used in situation when "towards" and "away from" should really be specified. So my preference would go towards using the existing S06 that matches the radial velocity positive direction.

**Comment by bodcmahe** [comment]
@roy-lowry  @gwemon 

Thank you both for your valuable input here - I think I have enough to proceed now.

Mark

**Comment by bodcmahe** [comment]
3 codes created in P01:
HFRVWC01 - Radial velocity (away from) of water current relative to instrument in the water body by high frequency radar
HFRVWD01 - Direction (from) of radial vector relative to instrument and True North in the water body by high frequency radar
CSERRVHF -  Radial velocity (away from) standard error of water current relative to instrument in the water body by high frequency radar
