### ISSUE TITLE
NTR: Biological Parameters - Species Counts (BODCNVS-319)

### ISSUE THREAD

**Issue by tkeena** [nvs-vocabs/P01#52]
Hi,

Can I please request the following three terms to be created:

Count of Salmo salar (ITIS: 161996: WoRMS 127186 )[Stage: smolt] 
Count of Salmo  trutta (ITIS: 161997: WoRMS 127187)[Stage: smolt] 
Count of Anguilla anguilla (ITIS: 161128: WoRMS 126281)

Many thanks,
Tara

**Comment by gwemon** [comment]
The following 3 new P01 codes have been queued for publication on the NVS:
AA241SC1	Count of Anguilla anguilla (ITIS: 161128: WoRMS 126281)
SS242TR1	Count of Salmo trutta (ITIS: 161997: WoRMS 127187) [Stage: smolt]
ST241SC1	Count of Salmo salar (ITIS: 161996: WoRMS 127186) [Stage: smolt]

**Comment by gwemon** [comment]
Hi @tkeena, Sorry for the long wait! All 3 codes are now available from the NVS.
[AA241SC1](https://vocab.nerc.ac.uk/collection/P01/current/AA241SC1) Count of Anguilla anguilla (ITIS: 161128: WoRMS 126281)
[SS242TR1](https://vocab.nerc.ac.uk/collection/P01/current/SS242TR1) Count of Salmo trutta (ITIS: 161997: WoRMS 127187) [Stage: smolt]
[ST241SC1](https://vocab.nerc.ac.uk/collection/P01/current/ST241SC1) Count of Salmo salar (ITIS: 161996: WoRMS 127186) [Stage: smolt]
