### ISSUE TITLE
NTR: SAMPLE VOLUME AS ESTIMATED BY SAMPLING DEPTH (BODCNVS-872)

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/P01#55]
Hi all, 

I'm working on a dataset where a Bongo sampling instrument was used. Volume of filtered sea water is estimated from both a [flowmeter](http://vocab.nerc.ac.uk/collection/P09/current/VOLF/) as well as from the depth-estimate. I'd like to discuss the addition of the following new term:

**Preferred Label**: SAMPLE VOLUME AS ESTIMATED BY (ESTIMATED) SAMPLING DEPTH
**Alternative Label**: Sample volume (filtration) as estimated from sampling depth estimate
**Definition**:  The volume of water filtered by a sampling device during its deployment, measured as a multiplication of sampling instrument mouth opening by sampling depth. 
**Related**: Liters - http://vocab.nerc.ac.uk/collection/P06/current/ULIT/
                    Cubic metres - http://vocab.nerc.ac.uk/collection/P06/current/MCUB/

I apologize if this is not the correct vocabulary / repository to post this in; but it seemed to follow the definition as found under http://vocab.nerc.ac.uk/collection/P01/current/VOLFFMXX/ . Looking forward to discussing this option further.

Thanks!

**Comment by timvdstap** [comment]
Hi everyone, would it be possible to get an update on this GitHub issue? Seems to have fallen off the radar, hoping to update an/some OBIS record(s) with the controlled vocabulary if possible.

**Comment by gwemon** [comment]
Apologies for delay @timvdstap and thank you for reminding us. If this term is to populate the header or title of a field that will hold the volume sampled as a variable then yes, this is the correct vocabulary. I am going to discuss your request with colleagues this morning.

**Comment by gwemon** [comment]
My first thoughts are:
http://vocab.nerc.ac.uk/collection/P01/current/VOLFFMXX/ is not yet modeled using the BODC PUV semantic model. My suggestion would be:
S06= Volume
S29= sample
S26= water body
S05= "computation from sampling device flowmeter reading and deployment time"
Giving a P01 label of "Volume of sample from a water body by computation from sampling device flowmeter reading and deployment time"

We have 4 other similar codes related to volume sampled and which will also need to be modeled according to the same logic (see 
http://vocab.nerc.ac.uk/search_nvs/P01/?searchstr=sample%25volume&options=identifier,preflabel,altlabel,status_accepted&rbaddfilter=inc&searchstr2=
).

So for your alternative method, this could give us:
"Volume of sample from a water body by computation from device geometry and sampling depth"
But I will confirm once we had a chance to discuss it.

**Comment by timvdstap** [comment]
Thanks @gwemon, that looks good!

**Comment by gwemon** [comment]
@timvdstap Hi Tim, sorry again this got overlooked. We discussed it today and we're proposing to make the method slightly broader to cater for both horizontal and vertical trawls. Would the following work for you:
"Volume of sample from a water body by computation from device geometry and estimated distance travelled"
where "computation from device geometry and estimated distance travelled" would be a new S05 term defined as: "The parameter (e.g. volume sampled) was derived from the known dimensions of the sampling device geometry and an estimate of the sampling depth or distance travelled while sampling."

**Comment by danibodc** [comment]
The following terms have been loaded to P01 and will be live on the NVS from tomorrow morning:

**VOLFFMDT**	Volume of sample (filtered) from the water body by computation from sampling device flowmeter reading and deployment time
**VOLFDGDT**	Volume of sample (filtered) from the water body by computation from sampling device geometry and estimated distance travelled

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/P01/current/VOLFFMDT/
https://vocab.nerc.ac.uk/collection/P01/current/VOLFDGDT/
