### ISSUE TITLE
NTR: New zooplankton abundance codes (BODCNVS-762)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#60]
The following new P01 parameter codes have been queued for publication on the NVS:

Date created | P01 URI | P01 preferred label | P02 group
-- | -- | -- | --
19/02/2021 | [AAC09437](http://vocab.nerc.ac.uk/collection/P01/current/AAC09437) | Abundance of Acanthephyra pelagica (WoRMS 107581) per unit volume of the   water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AAE09376](http://vocab.nerc.ac.uk/collection/P01/current/AAE09376) | Abundance of Aetideopsis (ITIS: 85414: WoRMS 104111) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AAE09405](http://vocab.nerc.ac.uk/collection/P01/current/AAE09405) | Abundance of Aetideus australis (ITIS: 779915: WoRMS 341238) [Stage:   adult Sex: female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AAE09457](http://vocab.nerc.ac.uk/collection/P01/current/AAE09457) | Abundance of Aetideus (ITIS: 85419: WoRMS 104112) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AAN09378](http://vocab.nerc.ac.uk/collection/P01/current/AAN09378) | Abundance of Andaniotes (WoRMS 101751) per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AAR09364](http://vocab.nerc.ac.uk/collection/P01/current/AAR09364) | Abundance of Arctapodema antarctica (WoRMS 174734) per unit volume of the   water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AAR09365](http://vocab.nerc.ac.uk/collection/P01/current/AAR09365) | Abundance of Arctapodema (WoRMS 117214) per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ABA09390](http://vocab.nerc.ac.uk/collection/P01/current/ABA09390) | Abundance of Balanidae (ITIS: 89599: WoRMS 106057) [Stage: cypris] per   unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ABE09379](http://vocab.nerc.ac.uk/collection/P01/current/ABE09379) | Abundance of Beroe cucumis (WoRMS 106358) per unit volume of the water   body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ABO09439](http://vocab.nerc.ac.uk/collection/P01/current/ABO09439) | Abundance of Botrynema brucei (WoRMS 117615) per unit volume of the water   body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACA09366](http://vocab.nerc.ac.uk/collection/P01/current/ACA09366) | Abundance of Calanidae (ITIS: 85259: WoRMS 10479) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACA09387](http://vocab.nerc.ac.uk/collection/P01/current/ACA09387) | Abundance of Cavolinioidea (WoRMS 411903) per unit volume of the water   body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACA09397](http://vocab.nerc.ac.uk/collection/P01/current/ACA09397) | Abundance of Candacia (ITIS: 86020: WoRMS 104157) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACA09398](http://vocab.nerc.ac.uk/collection/P01/current/ACA09398) | Abundance of Candacia maxima (WoRMS 342438) [Stage: adult Sex: female]   per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACA09404](http://vocab.nerc.ac.uk/collection/P01/current/ACA09404) | Abundance of Calycopsis (WoRMS 117028) per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACA09414](http://vocab.nerc.ac.uk/collection/P01/current/ACA09414) | Abundance of Caridea (ITIS: 96106: WoRMS 106674) [Stage: larvae] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACA09449](http://vocab.nerc.ac.uk/collection/P01/current/ACA09449) | Abundance of Calanoida (ITIS: 85258: WoRMS 1100) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACL09372](http://vocab.nerc.ac.uk/collection/P01/current/ACL09372) | Abundance of Clausocalanidae (ITIS: 610015: WoRMS 104082) [Stage:   copepodites C4] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACL09406](http://vocab.nerc.ac.uk/collection/P01/current/ACL09406) | Abundance of Clausocalanidae (ITIS: 610015: WoRMS 104082) [Stage:   copepodites C5] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACL09410](http://vocab.nerc.ac.uk/collection/P01/current/ACL09410) | Abundance of Clausocalanidae (ITIS: 610015: WoRMS 104082) [Stage: adult   Sex: female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACL09428](http://vocab.nerc.ac.uk/collection/P01/current/ACL09428) | Abundance of Clausocalanus laticeps (ITIS: 610035: WoRMS 342444) [Stage:   adult Sex: female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACT09381](http://vocab.nerc.ac.uk/collection/P01/current/ACT09381) | Abundance of Ctenocalanus (ITIS: 85362: WoRMS 104162) [Stage: copepodites   C4] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACT09394](http://vocab.nerc.ac.uk/collection/P01/current/ACT09394) | Abundance of Ctenocalanus (ITIS: 85362: WoRMS 104162) [Stage: copepodites   C5] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACT09400](http://vocab.nerc.ac.uk/collection/P01/current/ACT09400) | Abundance of Ctenocalanus (ITIS: 85362: WoRMS 104162) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACT09415](http://vocab.nerc.ac.uk/collection/P01/current/ACT09415) | Abundance of Ctenocalanus (ITIS: 85362: WoRMS 104162) [Stage: adult Sex:   male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ACT09464](http://vocab.nerc.ac.uk/collection/P01/current/ACT09464) | Abundance of Ctenocalanus (ITIS: 85362: WoRMS 104162) [Stage: copepodites   C3] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEC09402](http://vocab.nerc.ac.uk/collection/P01/current/AEC09402) | Abundance of Echinodermata (ITIS: 156857: WoRMS 1806) [Stage: nauplii]   per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09369](http://vocab.nerc.ac.uk/collection/P01/current/AEU09369) | Abundance of Eucalanidae (WoRMS 104085) per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09373](http://vocab.nerc.ac.uk/collection/P01/current/AEU09373) | Abundance of Euchaetidae (WoRMS 104086) [Stage: nauplii] per unit volume   of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09374](http://vocab.nerc.ac.uk/collection/P01/current/AEU09374) | Abundance of Euphausia superba (ITIS: 95514: WoRMS 236217) [Stage: adult   Sex: female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09382](http://vocab.nerc.ac.uk/collection/P01/current/AEU09382) | Abundance of Euchirella (ITIS: 85451: WoRMS 104120) [Stage: copepodites   C3] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09388](http://vocab.nerc.ac.uk/collection/P01/current/AEU09388) | Abundance of Euchirella (ITIS: 85451: WoRMS 104120) [Stage: copepodites   C2] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09391](http://vocab.nerc.ac.uk/collection/P01/current/AEU09391) | Abundance of Euphausia superba (ITIS: 95514: WoRMS 236217) [Stage: adult   Sex: male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09392](http://vocab.nerc.ac.uk/collection/P01/current/AEU09392) | Abundance of Euphausiacea (ITIS: 95496: WoRMS 1128) [Stage: adult Sex:   male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09395](http://vocab.nerc.ac.uk/collection/P01/current/AEU09395) | Abundance of Euphausia triacantha (ITIS: 95518: WoRMS 236220) [Stage:   adult Sex: female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09401](http://vocab.nerc.ac.uk/collection/P01/current/AEU09401) | Abundance of Euphausia frigida (ITIS: 95517: WoRMS 236218) [Stage:   juvenile] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09407](http://vocab.nerc.ac.uk/collection/P01/current/AEU09407) | Abundance of Euchirella (ITIS: 85451: WoRMS 104120) [Stage: copepodites   C4] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09413](http://vocab.nerc.ac.uk/collection/P01/current/AEU09413) | Abundance of Euchaetidae (WoRMS 104086) [Stage: copepodites C1] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09416](http://vocab.nerc.ac.uk/collection/P01/current/AEU09416) | Abundance of Euphausiacea (ITIS: 95496: WoRMS 1128) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09423](http://vocab.nerc.ac.uk/collection/P01/current/AEU09423) | Abundance of Euchaetidae (WoRMS 104086) [Stage: copepodites C3] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09426](http://vocab.nerc.ac.uk/collection/P01/current/AEU09426) | Abundance of Euphausia (ITIS: 95501: WoRMS 110673) [Stage: adult Sex:   male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09429](http://vocab.nerc.ac.uk/collection/P01/current/AEU09429) | Abundance of Euphausia frigida (ITIS: 95517: WoRMS 236218) [Stage: adult   Sex: male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09431](http://vocab.nerc.ac.uk/collection/P01/current/AEU09431) | Abundance of Euphausia frigida (ITIS: 95517: WoRMS 236218) [Stage: adult   Sex: female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09432](http://vocab.nerc.ac.uk/collection/P01/current/AEU09432) | Abundance of Euphausia triacantha (ITIS: 95518: WoRMS 236220) [Stage:   juvenile] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09434](http://vocab.nerc.ac.uk/collection/P01/current/AEU09434) | Abundance of Euchaetidae (WoRMS 104086) [Stage: copepodites C4] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09445](http://vocab.nerc.ac.uk/collection/P01/current/AEU09445) | Abundance of Eucalanidae (WoRMS 104085) [Stage: copepodites C2] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09450](http://vocab.nerc.ac.uk/collection/P01/current/AEU09450) | Abundance of Euchaetidae (WoRMS 104086) [Stage: copepodites C5] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09451](http://vocab.nerc.ac.uk/collection/P01/current/AEU09451) | Abundance of Eusirus antarcticus (WoRMS 237719) per unit volume of the   water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09452](http://vocab.nerc.ac.uk/collection/P01/current/AEU09452) | Abundance of Euphausia triacantha (ITIS: 95518: WoRMS 236220) [Stage:   adult Sex: male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09458](http://vocab.nerc.ac.uk/collection/P01/current/AEU09458) | Abundance of Eucalanidae (WoRMS 104085) [Stage: copepodites C1] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09459](http://vocab.nerc.ac.uk/collection/P01/current/AEU09459) | Abundance of Eucalanidae (WoRMS 104085) [Stage: copepodites C3] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09460](http://vocab.nerc.ac.uk/collection/P01/current/AEU09460) | Abundance of Euchaetidae (WoRMS 104086) [Stage: copepodites C2] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09461](http://vocab.nerc.ac.uk/collection/P01/current/AEU09461) | Abundance of Euchirella tunicata (WoRMS 104304) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AEU09465](http://vocab.nerc.ac.uk/collection/P01/current/AEU09465) | Abundance of Euphausia (ITIS: 95501: WoRMS 110673) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AFI09393](http://vocab.nerc.ac.uk/collection/P01/current/AFI09393) | Abundance of Fish (WoRMS 11676) [Stage: juvenile] per unit volume of the   water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AGA09456](http://vocab.nerc.ac.uk/collection/P01/current/AGA09456) | Abundance of Gaetanus (ITIS: 85467: WoRMS 104121) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AHA09368](http://vocab.nerc.ac.uk/collection/P01/current/AHA09368) | Abundance of Halistemma rubrum (WoRMS 135490) [Subcomponent: bracts] per   unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AHA09375](http://vocab.nerc.ac.uk/collection/P01/current/AHA09375) | Abundance of Haloptilus ocelatus (WoRMS 342624) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AHA09417](http://vocab.nerc.ac.uk/collection/P01/current/AHA09417) | Abundance of Haloptilus ocellatus (WoRMS 342624) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AHA09440](http://vocab.nerc.ac.uk/collection/P01/current/AHA09440) | Abundance of Haloptilus oxycephalus (ITIS: 85977: WoRMS 104434) [Stage:   adult Sex: female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AHA09443](http://vocab.nerc.ac.uk/collection/P01/current/AHA09443) | Abundance of Halistemma rubrum (WoRMS 135490) [Subcomponent: nectophores]   per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AHE09370](http://vocab.nerc.ac.uk/collection/P01/current/AHE09370) | Abundance of Heterorhabdus robustus (WoRMS 104581) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AHE09424](http://vocab.nerc.ac.uk/collection/P01/current/AHE09424) | Abundance of Heterorhabdus austrinus (WoRMS 343728) [Stage: adult Sex:   male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AHE09438](http://vocab.nerc.ac.uk/collection/P01/current/AHE09438) | Abundance of Heterorhabdus austrinus (WoRMS 343728) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AHE09453](http://vocab.nerc.ac.uk/collection/P01/current/AHE09453) | Abundance of Heterorhabdidae (ITIS: 85907: WoRMS 104087) [Stage: nauplii]   per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ALU09418](http://vocab.nerc.ac.uk/collection/P01/current/ALU09418) | Abundance of Lubbockia (ITIS: 88535: WoRMS 128672) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AME09380](http://vocab.nerc.ac.uk/collection/P01/current/AME09380) | Abundance of Mertensia (WoRMS 106341) per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AME09386](http://vocab.nerc.ac.uk/collection/P01/current/AME09386) | Abundance of Metridia curticauda (ITIS: 85738: WoRMS 104628) [Stage:   copepodites C5] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AME09389](http://vocab.nerc.ac.uk/collection/P01/current/AME09389) | Abundance of Metridiidae (WoRMS 100678) [Stage: copepodites C3] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AME09408](http://vocab.nerc.ac.uk/collection/P01/current/AME09408) | Abundance of Metridiidae (WoRMS 100678) [Stage: copepodites C1] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AME09425](http://vocab.nerc.ac.uk/collection/P01/current/AME09425) | Abundance of Metridiidae (WoRMS 100678) [Stage: nauplii] per unit volume   of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AME09442](http://vocab.nerc.ac.uk/collection/P01/current/AME09442) | Abundance of Metridiidae (WoRMS 100678) [Stage: copepodites C2] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AME09444](http://vocab.nerc.ac.uk/collection/P01/current/AME09444) | Abundance of Metridia gerlachei (ITIS: 85750: WoRMS 344689) [Stage:   copepodites C5] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AME09446](http://vocab.nerc.ac.uk/collection/P01/current/AME09446) | Abundance of Metridia curticauda (ITIS: 85738: WoRMS 104628) [Stage:   adult Sex: female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AME09466](http://vocab.nerc.ac.uk/collection/P01/current/AME09466) | Abundance of Metridia (ITIS: 85734: WoRMS 104190) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ANO09455](http://vocab.nerc.ac.uk/collection/P01/current/ANO09455) | Abundance of Nototheniops larseni (WoRMS 313400) per unit volume of the   water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AOP09409](http://vocab.nerc.ac.uk/collection/P01/current/AOP09409) | Abundance of Oplophorus spinosu (WoRMS 107602) per unit volume of the   water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [APE09430](http://vocab.nerc.ac.uk/collection/P01/current/APE09430) | Abundance of Peracle (WoRMS 138327) per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [APL09411](http://vocab.nerc.ac.uk/collection/P01/current/APL09411) | Abundance of Pleuromamma antarctica (WoRMS 345241) [Stage: adult Sex:   male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [APL09433](http://vocab.nerc.ac.uk/collection/P01/current/APL09433) | Abundance of Pleuromamma antarctica (WoRMS 345241) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [APL09448](http://vocab.nerc.ac.uk/collection/P01/current/APL09448) | Abundance of Pleuromamma (ITIS: 85751: WoRMS 104191) [Stage: copepodites   C5] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [APS09447](http://vocab.nerc.ac.uk/collection/P01/current/APS09447) | Abundance of Pseudocalanidae (ITIS: 85351: WoRMS 149739) per unit volume   of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ARA09367](http://vocab.nerc.ac.uk/collection/P01/current/ARA09367) | Abundance of Racovitzanus antarcticus (WoRMS 104784) [Stage: copepodites   C5] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ARA09383](http://vocab.nerc.ac.uk/collection/P01/current/ARA09383) | Abundance of Racovitzanus antarcticus (WoRMS 104784) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ARA09412](http://vocab.nerc.ac.uk/collection/P01/current/ARA09412) | Abundance of Racovitzanus antarcticus (WoRMS 104784) [Stage: copepodites   C4] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ARH09371](http://vocab.nerc.ac.uk/collection/P01/current/ARH09371) | Abundance of Rhincalanus (ITIS: 85316: WoRMS 104172) [Stage: copepodites   C4] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ARH09427](http://vocab.nerc.ac.uk/collection/P01/current/ARH09427) | Abundance of Rhincalanus (ITIS: 85316: WoRMS 104172) [Stage: copepodites   C3] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ARH09436](http://vocab.nerc.ac.uk/collection/P01/current/ARH09436) | Abundance of Rhincalanus (ITIS: 85316: WoRMS 104172) [Stage: copepodites   C2] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ASC09384](http://vocab.nerc.ac.uk/collection/P01/current/ASC09384) | Abundance of Scaphocalanus elongatus (WoRMS 104794) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ASP09399](http://vocab.nerc.ac.uk/collection/P01/current/ASP09399) | Abundance of Spinocalanus abyssalis (ITIS: 85392: WoRMS 104846) [Stage:   adult Sex: male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ASP09441](http://vocab.nerc.ac.uk/collection/P01/current/ASP09441) | Abundance of Spinocalanus (ITIS: 85390: WoRMS 104173) [Stage: adult Sex:   male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ASU09462](http://vocab.nerc.ac.uk/collection/P01/current/ASU09462) | Abundance of Subeucalanus (WoRMS 104173) [Stage: copepodites C3] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATH09377](http://vocab.nerc.ac.uk/collection/P01/current/ATH09377) | Abundance of Thysanoessa macrura (WoRMS 236219) [Stage: adult Sex: male]   per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATH09396](http://vocab.nerc.ac.uk/collection/P01/current/ATH09396) | Abundance of Thaliacea (WoRMS 22626) [Stage: nauplii] per unit volume of   the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATH09419](http://vocab.nerc.ac.uk/collection/P01/current/ATH09419) | Abundance of Thysanoessa macrura (WoRMS 236219) [Stage: juvenile] per   unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATH09420](http://vocab.nerc.ac.uk/collection/P01/current/ATH09420) | Abundance of Thysanoessa (ITIS: 95571: WoRMS 110679) [Stage: adult Sex:   male] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATH09421](http://vocab.nerc.ac.uk/collection/P01/current/ATH09421) | Abundance of Thysanoessa (ITIS: 95571: WoRMS 110679) [Stage: juvenile]   per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATH09454](http://vocab.nerc.ac.uk/collection/P01/current/ATH09454) | Abundance of Thysanoessa (ITIS: 95571: WoRMS 110679) [Stage: adult Sex:   female] per unit volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATR09385](http://vocab.nerc.ac.uk/collection/P01/current/ATR09385) | Abundance of Triconia (WoRMS 128691) [Stage: adult Sex: female] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATR09403](http://vocab.nerc.ac.uk/collection/P01/current/ATR09403) | Abundance of Triconia (WoRMS 128691) [Stage: adult Sex: male] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATR09422](http://vocab.nerc.ac.uk/collection/P01/current/ATR09422) | Abundance of Triconia (WoRMS 128691) [Stage: copepodites C5] per unit   volume of the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [ATR09463](http://vocab.nerc.ac.uk/collection/P01/current/ATR09463) | Abundance of Triconia (WoRMS 128691) [Stage: nauplii] per unit volume of   the water body | Zooplankton taxonomy-related abundance per unit volume of the water   column
19/02/2021 | [AVA09435](http://vocab.nerc.ac.uk/collection/P01/current/AVA09435) | Abundance of Vanadis longissima (WoRMS 129766) per unit volume of the   water body | Zooplankton taxonomy-related abundance per unit volume of the water   column

**Comment by danibodc** [comment]
Terms are live on the NVS.
