### ISSUE TITLE
Request for Volume of an organism in mm3 with a spherical assumption (BODCNVS-1124)

### ISSUE THREAD

**Issue by PatriciaCabrera** [nvs-vocabs/P01#61]
Volume of an organism in mm3 with a spherical assumption (based on area and ESD)

Related to:
ESD -> http://vocab.nerc.ac.uk/collection/S06/current/S0600260/
Area (in digital image) -> https://github.com/nvs-vocabs/S06/issues/21
Cell volume -> http://vocab.nerc.ac.uk/collection/P01/current/CELLVOLM/

Term requested to be able to submit (plankton) image datasets to EUROBIS/EMODnet Biology

**Comment by gwemon** [comment]
Apologies it looks like this ticket was overlooked.

Could we model this as:
Preflabel: [Volume](http://vocab.nerc.ac.uk/collection/S06/current/S0600025) of biological entity specified elsewhere by [image analysis]([S0415](http://vocab.nerc.ac.uk/collection/S04/current/S0415))  and computation from Equivalent Spherical Diameter (ESD)?

Definition: The volume of a biological entity estimated from surface area measured by digital image analysis assuming spherical shape.

**Comment by PatriciaCabrera** [comment]
Hi, yes that fits perfectly. thank you!

**Comment by danibodc** [comment]
This term has been loaded to P01 and will be live on the NVS from tomorrow morning:

VOLBPESD	Volume of biological entity specified elsewhere by image analysis and computation from Equivalent Spherical Diameter (ESD)

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/P01/current/VOLBPESD/

**Comment by danibodc** [comment]
@PatriciaCabrera This term is now live on the NVS, many thanks!
