### ISSUE TITLE
request general terms for isotope measurements on biota (BODCNVS-1100)

### ISSUE THREAD

**Issue by msweetlove** [nvs-vocabs/P01#72]
To archive a dataset with isotope measurements on OBIS using the extended measurement or fact extension, I need (but could not find) the following general terms:

Enrichment of carbon-13 {13C CAS 14762-74-4} {delta(13)C} in biota by mass spectrometry (related to http://vocab.nerc.ac.uk/collection/P01/current/D13CWC18/)
Enrichment of nitrogen-15 {15N CAS 14390-96-6} {delta(15)N} in biota by mass spectrometry
Enrichment of sulfer-34 {34S CAS 13965-97-4} {delta(34)S} in biota by mass spectrometry
Ratio of total carbon {total_C CAS 7440-44-0} to total nitrogen in biota (same as MIXS:0000310 carb_nitro_ratio)
Concentration of total carbon {total_C CAS 7440-44-0} per unit dry weight of biota (related to http://vocab.nerc.ac.uk/collection/P01/current/TCCNXXXX/)
Concentration of total nitrogen {total_N} per unit dry weight of biota
Concentration of total sulfer {total_S} per unit dry weight of biota

I noticed during my search through NVS and NERC, that for some terms there seem to be related ones, like "Enrichment of carbon-13 {13C CAS 14762-74-4} {delta(13)C} in biota by mass spectrometry" is related to "Enrichment of carbon-13 {13C CAS 14762-74-4} {delta(13)C} in biota {Fish (WoRMS 11676) [Stage: larvae]} by mass spectrometry" (http://vocab.nerc.ac.uk/collection/P01/current/D13CWC18/), but this definition is overly precise. I think there is a need for more general definitions that do not mention the species or life stage. The species name, name ID and lifestage can go to different columns in darwin Core, so adding this information is completely redundant. Moreover, besides the fact that taxonomic names may change over time, there are nearly 9 million eukaryotic species, not even counting the more diverse groups like Bacteria and Archaea, so making definitions species specific where this is not necessary will make any vocabulary to big an impractical to use in the long run...

**Comment by ymgan** [comment]
Hello, I am wondering if there is any updates for this issue? Thank you!!

**Comment by gwemon** [comment]
@msweetlove @ymgan The BODC PUV or P01 vocabulary is used for the precise annotation of what was measured. Hence we avoid ambiguous or very generic codes. However the semantic model can support both types of data models: the one (like OBIS/DwC) where the species name is stored in a separate field and the one (like e.g [EMODnet chemistry for contaminants in biota](https://nodc.inogs.it/doi/documents/EMODnetChemistry_QC_Steps_Contaminants_4.2021.pdf)) where the species name and its attributes are captured within the P01 code definition itself. So, for the terms you requested we could create codes that use "biological entity specified elsewhere" as the biological entity related to the matrix "biota". Note that if any of the chemicals measured are measured in a specific body part then I would advise to use the [S12 vocabulary](http://vocab.nerc.ac.uk/collection/S12/current/) to futher define the biological entity.

For example, if your first term was measured in say, the liver of a biological entity that is described in the occurrence extension then we could have:
Enrichment of carbon-13 {13C CAS 14762-74-4} {delta(13)C} in biota {biological entity specified elsewhere [Subcomponent: liver]}
Are all your measurements on unspecified body parts or whole individuals?

**Comment by ymgan** [comment]
I see!! Thank you so much for the updates @gwemon!! 

The measurements were carried out on either the tegument or the podia of a seastar's arm.

**Comment by ymgan** [comment]
Hello, is there any update in this? Thanks a lot!

**Comment by gwemon** [comment]
Hi @ymgan can I ask is the body part on which these measurements are made significant? I know that for contaminants it is essential most of the time to specify where the measurement was made however is it the case for isotope enrichment? If not then we could simply propose the following new terms:
Enrichment of carbon-13 {13C CAS 14762-74-4} {delta(13)C} in biota {biological entity specified elsewhere} by mass spectrometry
Enrichment of nitrogen-15 {15N CAS 14390-96-6} {delta(15)N} in biota  {biological entity specified elsewhere} by mass spectrometry
Enrichment of sulphur-34 {34S CAS 13965-97-4} {delta(34)S} in biota  {biological entity specified elsewhere} by mass spectrometry ** new chemical entity entry needed in S27 vocab
For the ratio: are they atomic ratio or mass ratio?
Also we would not specify "total". Would the following fill your needs:
Mass/Atomic ratio of carbon/nitrogen in biota  {biological entity specified elsewhere}
Concentration of carbon {C} per unit dry weight of biota {biological entity specified elsewhere}
Concentration of nitrogen {N} per unit dry weight of biota  {biological entity specified elsewhere}
Concentration of sulphur {S} per unit dry weight of biota  {biological entity specified elsewhere}

**Comment by ymgan** [comment]
Hey, we have another dataset awaiting general vocab for isotopic measurements. 

Some of the isotope measurements are performed on sediment so having that with body part doesn't make sense, but the sediment is collected together with the organisms sampled.

**Comment by ymgan** [comment]
Hi Gwen, 

May I know if there is any update on this? We have datasets queuing for this vocabulary. Thanks a lot!

**Comment by gwemon** [comment]
Hi @ymgan, sorry for the long wait and thank you for the reminder. I will try and process your request this week.

**Comment by gwemon** [comment]
> Hey Gwen,
> 
> Thank you so much!! This is what I received from our data provider, not sure if this answered your question?
> 
> After discussed with my supervisor, we think it's better to go with the more general route where the body part is omitted from the vocabulary and the information will be specified under the `measurementRemarks` field.
> 
> Description	Unit
> The δ13C measured in the tegument of the considered sea star specimen, expressed in per mille and relative to the international reference Vienna Pee Dee Belemnite.	Per mille
> The δ15N measured in the tegument of the considered sea star specimen, expressed in per mille and relative to the international reference Atmospheric Air.	Per mille
> The δ34S measured in the tegument of the considered sea star specimen, expressed in per mille and relative to the international reference Vienna Canyon Diablo Troilite.	Per mille
> The ratio between carbon and nitrogen elemental contents measured in the tegument of the considered sea star specimen, expressed as mass ratio.	Unitless
> The nitrogen elemental content measured in the tegument of the considered sea star specimen, expressed in relative percentage of dry mass.	Relative percentage of dry mass
> The carbon elemental content measured in the tegument of the considered sea star specimen, expressed in relative percentage of dry mass.	Relative percentage of dry mass
> The sulfur elemental content measured in the tegument of the considered sea star specimen, expressed in relative percentage of dry mass.	Relative percentage of dry mass

Hi @ymgan I am creating these codes today. The definition or description of the codes cannot be more specific than the preferred label so I will not be referring to the fact that these measurements are on the tegument of a sea star but just that they were made on biota which is specified elsewhere in the data schema.

**Comment by gwemon** [comment]
The following codes have been created and queued for publication on the NVS:
C13BTX01	Enrichment with respect to Vienna Pee Dee Belemnite (VPDB) of carbon-13 {13C CAS 14762-74-4} {delta(13)C} in biota {biological entity specified elsewhere} by mass spectrometry
N15BTX01	Enrichment of nitrogen-15 {15N CAS 14390-96-6} {delta(15)N} in biota {biological entity specified elsewhere} by mass spectrometry
S34BTX01	Enrichment with respect to VCDT of sulfur-34 {34S CAS 13965-97-4} {delta(34)S} in biota {biological entity specified elsewhere} by mass spectrometry

**Comment by gwemon** [comment]
@ymgan all the terms above are now live on the NVS. We are only missing the C:N ratio. We have to do a small database modification in order to accommodate this kind of parameters (i.e. ratio of substances as opposed to substances in biota in our (no longer so new but still evolving!) semantic model. It should not take us long to do that. I'll pig you as soon as the missing code is in. Many thanks, Gwen.

**Comment by ymgan** [comment]
Hey @gwemon 

Quick question, is https://vocab.nerc.ac.uk/collection/S18/current/S1800098/ the vocab for C:N ratio?

**Comment by gwemon** [comment]
Hi @ymgan No,  not yet. The S18 term is just one of the building block to the P01 complex term. I needed to create an extension to our model in order to enable the ratio of 2 chemical entities into the P01 semantic model. The extension is now implemented but I haven't got round to creating the P01 code yet. I will do that as soon as I can.

**Comment by ymgan** [comment]
okie!! Thank you so much for working on this! I appreciate it!

**Comment by gwemon** [comment]
A new P01 concept with identifier CNBIOENT has been created and will queued for overnight publication on the NVS.

**Comment by gwemon** [comment]
https://vocab.nerc.ac.uk/collection/P01/current/CNBIOENT/
