### ISSUE TITLE
request term: Arm length of a sea star (BODCNVS-1117)

### ISSUE THREAD

**Issue by msweetlove** [nvs-vocabs/P01#73]
term request:
Arm length of a sea star (Asteroidea, WoRMS 123080)

Definition:
A standard arm length measurement used in sea start biometric studies and taken as the distance measured from the tip of the a median sized arm to the center of the oral disc.

Related: Length (fork length) of biological entity specified elsewhere
http://vocab.nerc.ac.uk/collection/P01/current/FL01XX01/

**Comment by ymgan** [comment]
Hello, may I know if there is any update regarding this? thank you!

**Comment by gwemon** [comment]
SFAINDLX	Length of biological entity specified elsewhere [Subcomponent: starfish arm] queued for publication
with definition: The arm length of a starfish (also known as sea stars) identified elsewhere in the metadata.

**Comment by gwemon** [comment]
Term now available from the NVS: https://vocab.nerc.ac.uk/collection/P01/current/SFAINDLX/
