### ISSUE TITLE
request term: disc radius of a sea star (BODCNVS-1115)

### ISSUE THREAD

**Issue by msweetlove** [nvs-vocabs/P01#74]
term request:
Disc radius of a sea star (Asteroidea, WoRMS 123080)

Definition:
A standard disc radius measurement used in sea star biometric studies and taken as the distance measured center to the outer edge of the oral disc.

Related: Length (fork length) of biological entity specified elsewhere
http://vocab.nerc.ac.uk/collection/P01/current/FL01XX01/

**Comment by ymgan** [comment]
Hello, is there any update in this? Thank you!

**Comment by gwemon** [comment]
Thank you @ymgan for the prompt and apologies for the lack of action on this. I think that the best way to model this is to use S06=[Radius](http://vocab.nerc.ac.uk/collection/S06/current/S0600251/) and create a new biological entity Subcomponent (S12 collection) term for "central disc"
This could be defined as: "The central body part of a starfish (Asteroidea) also known as sea star, containing the internal organs, and the mouth and anus, and from which arms arms radiate. The radius of the central disc is used as a standard biometric measurement in starfish studies."

**Comment by gwemon** [comment]
New biological entity (S25) term compiled and queued for publication on the NVS: 
BE009541	biological entity specified elsewhere [Subcomponent: central disc]

**Comment by gwemon** [comment]
@ymgan 
New P01 compiled and queued for publication: 
SSCD1RAD	Radius of biological entity specified elsewhere [Subcomponent: central disc]
Will be available on the NVS after 0730 London time tomorrow morning.

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/P01/current/SSCD1RAD/
