### ISSUE TITLE
Request for Width (in digital image) of biological entity specified elsewhere (BODCNVS-1122)

### ISSUE THREAD

**Issue by PatriciaCabrera** [nvs-vocabs/P01#75]
Term request:
Width (in digital image) of biological entity specified elsewhere.

Definition:
The width of the digital representation of an organism in a digital image measured in number of pixels.

Related: Length (in digital image) of biological entity specified elsewhere
http://vocab.nerc.ac.uk/collection/P01/current/LGPIXEL1/

**Comment by gwemon** [comment]
New P01 code created and queued for publication tomorrow morning 6:30AM UTC:
WDPIXEL1	Width (in digital image) of biological entity specified elsewhere
