### ISSUE TITLE
NTR: Biological species counts (BODCNVS-1055)

### ISSUE THREAD

**Issue by tkeena** [nvs-vocabs/P01#77]
Hi,

Can I please request the following two terms to be created:

Count of Salmo salar (ITIS: 161996: WoRMS 127186 )[Stage: adult] 
Count of Salmo trutta (ITIS: 161997: WoRMS 127187)[Stage: adult] 

Kind regards,
Tara

**Comment by gwemon** [comment]
2 new P01 combinations created and queued for publication on the NVS:
AT241SC1	Count of Salmo trutta (ITIS: 161997: WoRMS 127187) [Stage: adult]
AS242TR1	Count of Salmo salar (ITIS: 161996: WoRMS 127186) [Stage: adult]
