### ISSUE TITLE
NTR: Request for Bell diameter (BODCNVS-875)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P01#78]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Bell diameter <p><b>Definition</b><p> Diameter of biological entity specified elsewhere [Subcomponent: bell]<p><H2> Optional </H2><p><b>Sources/references</b><p> Widmer, Chad L. "Effects of temperature on growth of north-east Pacific moon jellyfish ephyrae, Aurelia labiata (Cnidaria: Scyphozoa)." Marine Biological Association of the United Kingdom. Journal of the Marine Biological Association of the United Kingdom 85, no. 3 (2005): 569.<p>

**Comment by gwemon** [comment]
BELINDDM	Diameter of biological entity specified elsewhere [Subcomponent: bell] queued for publication on the NVS with definition: The length of a straight line passing from side to side through the bell of a jellyfish identified elsewhere in the metadata.

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/P01/current/BELINDDM/
