### ISSUE TITLE
NTR: Sauter mean diameter of particles in different SPM size classes

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#79]
We have received the following request:

SImilar to http://vocab.nerc.ac.uk/collection/P01/current/SMDMISGA/

"Sauter mean diameter in suspended particulate material 2.5-500um by
in-situ particle sizer" tool=LISST100X type B

"Sauter mean diameter in suspended particulate material 1.25-250um by
in-situ particle sizer" tool=LISST100X type A

"Sauter mean diameter in suspended particulate material 1.0-500um by
in-situ particle sizer" tool=LISST200X type A

**Comment by danibodc** [comment]
The following P01 terms have now been created:

SMDMISGB 
**Preferred label** - Sauter mean diameter of particles in suspended particulate material 1.25-250um by in-situ particle sizer
SMDMISGD 
**Preferred label** - Sauter mean diameter of particles in suspended particulate material 2.5-500um by in-situ particle sizer
SMDMISGC 
**Preferred label** - Sauter mean diameter of particles in suspended particulate material 1.0-500um by in-situ particle sizer

**Definition** - The average diameter of a collection of suspended particulate material having the same volume/surface ratio as a particle of interest, collected by in-situ particle sizer and determined by filtration through a pore filter and screen of specified pore size.

They will become live on the NVS from 0730 UTC tomorrow morning.

**Comment by danibodc** [comment]
These terms are now live on the NVS:

https://vocab.nerc.ac.uk/collection/P01/current/SMDMISGB/
https://vocab.nerc.ac.uk/collection/P01/current/SMDMISGC/
https://vocab.nerc.ac.uk/collection/P01/current/SMDMISGD/
