### ISSUE TITLE
NTR P01 Proportion of particles in the sediment...(BODCNVS-1077)

### ISSUE THREAD

**Issue by tkeena** [nvs-vocabs/P01#82]
Hi,

Can we please request the following P01s to be created. 

Proportion of particles  in the sediment >8mm
Proportion of particles  in the sediment 4-8mm
Proportion of particles in the sediment 2-4mm
Proportion of particles in the sediment 1-2mm
Proportion of particles in the sediment 0.5-1mm
Proportion of particles in the sediment 0.25-0.5mm
Proportion of particles in the sediment 125-250um
Proportion of particles in the sediment 62-125um
Proportion of particles in the sediment <63um

Many thanks,
Tara

**Comment by gwemon** [comment]
Hi Tara @tkeena , is this a proportion by volume? and is it the proportion of particles in this size range in the sediment? If so then the size range should be attached to the particles element rather than the matrix. So it would be similar construction to e.g. http://vocab.nerc.ac.uk/collection/P01/current/PRPCL066/
Do you agree?

**Comment by tkeena** [comment]
Hi Gwen @gwemon ,

Yes, I agree. That construction is more suitable. 
Many thanks,
Tara

**Comment by gwemon** [comment]
Hi Roseanna, @roswri Could you take this one on please? Using the procedure for creating new GP_MODEL codes from existing ones based on http://vocab.nerc.ac.uk/collection/P01/current/PRPCL066/ as a template. Note that a few codes like e.g. http://vocab.nerc.ac.uk/collection/P01/current/PRPCL088/ for <63um
may already exist. Also as a convention we standardise all particle sizes to micrometres.

**Comment by roswri** [comment]
Hi Tara @tkeena,

I found the following codes already existed:

Proportion by volume of particles (4000-8000um) in the sediment	
http://vocab.nerc.ac.uk/collection/P01/current/PRPCL220/

Proportion by volume of particles (2000-4000um) in the sediment	
http://vocab.nerc.ac.uk/collection/P01/current/PRPCL218/

Proportion by volume of particles (1000-2000um) in the sediment	
http://vocab.nerc.ac.uk/collection/P01/current/PRPCL207/

Proportion by volume of particles (500-1000um) in the sediment	
http://vocab.nerc.ac.uk/collection/P01/current/PRPCL192/

Proportion by volume of particles (250-500um) in the sediment	
http://vocab.nerc.ac.uk/collection/P01/current/PRPCL176/

Proportion by volume of particles (125-250um) in the sediment	
http://vocab.nerc.ac.uk/collection/P01/current/PRPCL161/

Proportion by volume of particles (0-63um) in the sediment	
http://vocab.nerc.ac.uk/collection/P01/current/PRPCL088/

I have created a new code for: 
Proportion by volume of particles (>8000um) in the sediment	
http://vocab.nerc.ac.uk/collection/P01/current/PRPCL751/
The new term has been queued for publication but is not yet live. We currently have only one publication round per day and the next one will be shortly after 0700UT (AM) tomorrow.


I just wanted to check that you want a code for particles (62-125um) or if it was meant to be for particles (63-125um)?
If the latter, this code already exists:
Proportion by volume of particles (63-125um) in the sediment	
http://vocab.nerc.ac.uk/collection/P01/current/PRPCL147/
If not, let me know and I will create a new code for you!

Many thanks,
Roseanna

**Comment by gwemon** [comment]
@roswri it looks like the 62-125um might be a typo in Tara's original request. 
@tkeena  could you confirm please? If so then it looks like all the codes you needed are already in P01. Is that correct?

**Comment by tkeena** [comment]
Hi Roseanna. Thank you for following up on this. I checked with our Data Steward and they don't use proportion by volume. 
We're now going with the structure 'Proportion of particles (63-125um) in the sediment by particle sizer'. I think most exist but have a few ranges not yet included which I will request at a later stage. Thanks again for your help. Tara
