### ISSUE TITLE
NTR: glider phase and glider phase number (BODCNVS-1083)

### ISSUE THREAD

**Issue by bodcmahe** [nvs-vocabs/P01#83]
External request received from Michele Fichaut (Ifremer), who is coordinating efforts to incorporate glider data held in the EGO GDAC (Coriolis) into SeaDataNet (SDN). EGO NetCDFs will be converted into SDN trajectory format with the suggestion that EGO PHASE and PHASE_NUMBER variables are represented in SDN data files by new P01 terms. 

Background to PHASE and PHASE_NUMBER is available in the EGO gliders NetCDF format reference manual, with the 7 recognised EGO glider phases captured in the manual's reference tables (reference manual published at https://doi.org/10.13155/34980). 

Ifremer's suggested approach discussed within BODC and supported. 

Proposed P01 modelling:

1) PHASE

Effectively 'identifiers' of glider 'phases' when glider is in water, based on a known published methodology and reference table (currently reference table 9.2 in EGO manual v1.4).  

'Identifier' already present in S06 - http://vocab.nerc.ac.uk/collection/S06/current/S0600156/

Propose combining with new S29 term request for 'glider phase' and new S05 methodology referencing the EGO manual DOI. The reference table for phase definitions is a possible candidate for an OceanGliders-governed collection in due course, at which point the S05 term can be elaborated.

In summary:
e.g. Identifier of glider phase by classification using the EGO format reference manual (https://doi.org/10.13155/34980)

2) PHASE_NUMBER

Again, documented in the EGO reference manual. Phase number being described as: 

'A number associated with the phase. The first phase number is 0. The phase number is increased at each phase change.'

This is effectively a sequence number and will prove very useful if glider trajectory files need to be subset into trajectory profiles as part of SeaDataNet product assembly. 

Some guidance would be appreciated here. I am thinking the same S29 and S05 terms outlined above, but with an alternative S06. 'Count' doesn't seem right. I was hoping to get inspiration from ADCP bin number (P01=BINNUMBR), but this has yet to be constrained against the new semantic model.

**Comment by gwemon** [comment]
@bodcmahe Thaks for this. We already have a number of P01 concepts that relate to various kinds of sequence numbers however they are still in the old semantic model format. So we do not yet have a S06 property set up for it. I do believe that a new Property for "Sequence number" would be a good move and would enable us to remodel the following codes using the new semantic model where:
http://vocab.nerc.ac.uk/collection/P01/current/ACYCAA01/ could become "Sequence number of data record"
http://vocab.nerc.ac.uk/collection/P01/current/FIRSEQID/ could become "Sequence number of bottle firing"
http://vocab.nerc.ac.uk/collection/P01/current/SQNOIRCN/ could become "Sequence number of connection attempts by Iridium telecommunications"

So if we go for that, then we will also need a new (property vocab) for "Sequence number". I'll create that ticket in the S06 repo.

**Comment by bodcmahe** [comment]
Thanks @gwemon - sequence number sounds like a sensible suggestion...

**Comment by danibodc** [comment]
I have now created these terms:

**Code:** SQGLPH01	
**Preferred label:** Sequence number of glider phase by classification to a term from the Everyone's Gliding Observatories (EGO) format reference list (https://doi.org/10.13155/34980)	
**Description:** A numeric integer term assigned to specific data cycles associated with the phase of glider operation, defined using the Everyone's Gliding Observatories (EGO) format reference list (https://doi.org/10.13155/34980). The first sequence number is 0 and it is increased at each phase change.

**Code:** IDGLPH01	
**Preferred label:** Identifier of glider phase by classification to a term from the Everyone's Gliding Observatories (EGO) format reference list (https://doi.org/10.13155/34980)	
**Description:** A numeric integer term describing the phase of glider operation defined using the Everyone's Gliding Observatories (EGO) format reference list (https://doi.org/10.13155/34980).

They will be live on the NVS from 0730 UTC tomorrow morning.

**Comment by danibodc** [comment]
These codes are now live:

https://vocab.nerc.ac.uk/collection/P01/current/IDGLPH01/
https://vocab.nerc.ac.uk/collection/P01/current/SQGLPH01/
