### ISSUE TITLE
NTR: Request for mantle length (BODCNVS-876)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P01#84]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>mantle length <p><b>Definition</b><p> Length of biological entity specified elsewhere [Subcomponent: mantle]<p><H2> Optional </H2><p><b>Sources/references</b><p> Forsythe, J. W., and R. T. Hanlon. "Growth of the eastern Atlantic squid, Loligo forbesi Steenstrup (Mollusca: Cephalopoda)." Aquaculture Research 20, no. 1 (1989): 1-14.<p>

**Comment by gwemon** [comment]
@roswri  could you create the following P01 based on existing http://vocab.nerc.ac.uk/collection/P01/current/OBSINDLX/

The resulting combined P01 label will be of the form: "Length of biological entity specified elsewhere [Subcomponent: mantle]"

Codalt (DML)

Proposed definition: A standard size measurement in coleid cephalopod morphometry. It is the length measured in a straight line over the dorsal midline of the mantle (or dorsal mantle length, DML), i.e. the cephalopod's "body" lying posterior to the head. A different P01 code needs to be used whenever for ventral mantle length is reported.

**Comment by roswri** [comment]
Code created: DML1XX01 - Length of biological entity specified elsewhere [Subcomponent: mantle]

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/P01/current/DML1XX01/
