### ISSUE TITLE
NTR: new P01 codes needed for contaminants in biota (BODCNVS-1087)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P01#94]
EMODnet chemistry request for new P01 codes for contaminants measured on Merluccius merluccius muscle tissue and Anisakis sp. (its parasite).

**Comment by roswri** [comment]
S27 terms required:
https://github.com/nvs-vocabs/S27/issues/8
https://github.com/nvs-vocabs/S27/issues/9
https://github.com/nvs-vocabs/S27/issues/10
https://github.com/nvs-vocabs/S27/issues/11
https://github.com/nvs-vocabs/S27/issues/12

**Comment by roswri** [comment]
Terms Created
[Abundance standard deviation of Synechococcus (ITIS: 773: WoRMS 160572) per unit volume of the water body by epifluorescence microscopy](http://vocab.nerc.ac.uk/collection/P01/current/P700MSDE)
[Abundance of Synechococcus (ITIS: 773: WoRMS 160572) per unit volume of the water body by epifluorescence microscopy](http://vocab.nerc.ac.uk/collection/P01/current/P700M90E)
[Abundance of Pelagonemertes rollestoni (WoRMS 148267) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/APE09205)
[Abundance of Gymnoscopelus microlampas (WoRMS 234717) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AGY09204)
[Abundance of Woodsia (WoRMS 271224) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AWO09206)
[Abundance of Argyropelecus (WoRMS 126196) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AAR09203)
[Abundance of Poromitra (WoRMS 126182) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/APO09201)
[Abundance of Pseudochaenichthys georgianus (WoRMS 234667) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/APS09202)
[Abundance of Crustacea (ITIS: 83677: WoRMS 1066) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ACR01605)
[Abundance of Euphausia hanseni (WoRMS 110685) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AEU09094)
[Abundance of Euphausia gibboides (WoRMS 110684) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AEU09114)
[Abundance of Euphausia recurva (WoRMS 221047) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AEU09115)
[Abundance of Fish (WoRMS 11676) [Subgroup: mesopelagic] per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AFI09117)
[Abundance of Halicreas minimum (WoRMS 117617) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AHA09095)
[Abundance of Halicreas (WoRMS 117108) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AHA09110)
[Abundance of Histioteuthis (WoRMS 138074) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AHI09096)
[Abundance of Howella sherborni (WoRMS 126995) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AHO09083)
[Abundance of Lampadena pontifex (WoRMS 272707) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ALA09116)
[Abundance of Leptocephalus (WoRMS 843623) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ALE09087)
[Abundance of Maresearsia praeclara (WoRMS 135460) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AMA09091)
[Abundance of Melanostomiinae (WoRMS 154229) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AME09084)
[Abundance of Metelectrona (WoRMS 206941) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AME09121)
[Abundance of Moerisiidae (WoRMS 22784) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AMO09099)
[Abundance of Moerisia (WoRMS 117166) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AMO09118)
[Abundance of Nausithoe punctata (WoRMS 135290) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ANA09085)
[Abundance of Nematobrachion (WoRMS 110675) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ANE09086)
[Abundance of Orchistoma (WoRMS 117176) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AOR09097)
[Abundance of Orchistoma pileus (WoRMS 285115) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AOR09119)
[Abundance of Oxycephalus (WoRMS 206128) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AOX09100)
[Abundance of Oxycephalus clausi (WoRMS 220731) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AOX09102)
[Abundance of Phrosina semilunata (WoRMS 103273) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/APH09098)
[Abundance of Physonectae (WoRMS 135335) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/APH09112)
[Abundance of Platyscelus (WoRMS 101807) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/APL09082)
[Abundance of Pterotracheoidea (WoRMS 387338) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/APT09111)
[Abundance of Pyrosoma (WoRMS 137224) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/APY09101)
[Abundance of Pyrosomatidae (WoRMS 137216) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/APY09103)
[Abundance of Sternoptychidae (ITIS: 162212: WoRMS 125603) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AST06374)
[Abundance of Symbolophorus (WoRMS 125833) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ASY09108)
[Abundance of Symbolophorus boops (WoRMS 217719) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ASY09109)
[Abundance of Teuthida (WoRMS 11716) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ATE09104)
[Abundance of Thysanoessa gregaria (WoRMS 110707) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ATH09120)
[Abundance of Electrona risso (WoRMS 126600) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AEL09107)
[Abundance of Diphyes dispar (WoRMS 135420) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ADI09113)
[Abundance of Diaphus (WoRMS 125819) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ADI09093)
[Abundance of Diaphus hudsoni (WoRMS 217693) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ADI09090)
[Abundance of Cyclosalpa pinnata (WoRMS 137260) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ACY09106)
[Abundance of Cymbulia peronii (WoRMS 139494) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ACY09092)
[Abundance of Colobonema sericeum (WoRMS 117854) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ACO09081)
[Abundance of Chelophyes (WoRMS 135360) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ACH09105)
[Abundance of Abylidae (WoRMS 135336) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/AAB09088)
[Abundance of Chrysaora (WoRMS 135261) per unit volume of the water body](http://vocab.nerc.ac.uk/collection/P01/current/ACH09089)
