### ISSUE TITLE
Typo on some Definitions: `fesh` (BODCNVS-1152)

### ISSUE THREAD

**Issue by fcarvalhopacheco** [nvs-vocabs/P01#95]
Hi,

I just wanted to point out some typos found in the Description of some parameters. 

```
Definition       ... a unit volume of any fesh or salt water body ...
```

I believe  `fesh` should be `fresh`

See the variables:

http://vocab.nerc.ac.uk/collection/P01/current/BBCAXXP1/1/
http://vocab.nerc.ac.uk/collection/P01/current/BECAXXP1/1/
http://vocab.nerc.ac.uk/collection/P01/current/CCXTXXP1/
http://vocab.nerc.ac.uk/collection/P01/current/PBAXXXP1/
http://vocab.nerc.ac.uk/collection/P01/current/PBAXXXP1/

Cheers
Fernando

**Comment by gwemon** [comment]
Hello Fernando @fcarvalhopacheco Thak you for reporting this. I have corrected it and it is now queued for our next publication round tomorrow 0630AM UTC. Many thanks. Gwen.

**Comment by fcarvalhopacheco** [comment]
Thank you @gwemon

**Comment by gwemon** [comment]
All current versions of the following terms are now correct
http://vocab.nerc.ac.uk/collection/P01/current/BBCAXXP1/
http://vocab.nerc.ac.uk/collection/P01/current/BECAXXP1/
http://vocab.nerc.ac.uk/collection/P01/current/CCXTXXP1/
http://vocab.nerc.ac.uk/collection/P01/current/PBAXXXP1/

@fcarvalhopacheco Please note that each P01 concept is version-controlled. So these URIs will now be the version 2 of each of these terms (i.e. see for example http://vocab.nerc.ac.uk/collection/P01/current/BBCAXXP1/2/ which is the same as http://vocab.nerc.ac.uk/collection/P01/current/BBCAXXP1/). 
The previous version is still accessible by adding the version number after the current URI. Hence the following URIs will still have the typo: 
http://vocab.nerc.ac.uk/collection/P01/current/BBCAXXP1/1/
http://vocab.nerc.ac.uk/collection/P01/current/BECAXXP1/1/
http://vocab.nerc.ac.uk/collection/P01/current/CCXTXXP1/1/
http://vocab.nerc.ac.uk/collection/P01/current/PBAXXXP1/1/
